import * as _path_ from 'path';
import {expect} from 'chai';
import * as _md5_ from 'md5';

import ModelClass from "../dist/src/ModelClass";
import {ModelObjectType} from "../dist/src/ModelType";
import ModelFile from "../dist/src/ModelFile";
import DataScope, {DataScopePpts} from "../dist/src/DataScope";

const TEST_WS:string = _path_.join(__dirname,'ws');
const TEST_APP = "eshard_test"

var BIN_SCOPE:DataScope = (new DataScope("bin")).setPpts(DataScopePpts.PATH, _path_.join(TEST_WS,TEST_APP,'apk'));
describe('ModelFile node', function() {



    before(function(){
    });

    beforeEach(function() {

    });

    afterEach(function() {

    });
    
    describe('new', function() {

        let m:ModelFile = null;

        before(function(){
            m = new ModelFile({
                path: _path_.join(TEST_WS,TEST_APP,'apk','lib','armeabi','libcrackmelib.so'),
                type: 'ELF',
                name: 'libcrackmelib.so',
                scope: BIN_SCOPE
            });
        });

        it('has UID autogenerated', function () {
            expect(m.getUID()).to.equals(_md5_(m.getPath()));
        });

        it('autoconf', function () {
            expect(m.path).to.equals(_path_.join(TEST_WS,TEST_APP,'apk','lib','armeabi','libcrackmelib.so'));
            expect(m.type).to.equals('ELF');
            expect(m.name).to.equals('libcrackmelib.so');
            expect(m.scope.getName()).to.equals("bin");
        });
    });

    describe('properties', function() {

        it('configuration pat', function () {
            

           // expect(p.nofrida).to.equals(0);
        });
    });
});