import * as _path_ from 'path';
import {expect} from 'chai';

import ModelClass from "../dist/src/ModelClass";
import {ModelObjectType} from "../dist/src/ModelType";
import ModelFile from "../dist/src/ModelFile";
import DataScope, {DataScopePpts} from "../dist/src/DataScope";

const TEST_WS:string = _path_.join(__dirname,'ws');
const TEST_APP = "eshard_test"

describe('ModelFile node', function() {

    let BIN_SCOPE:DataScope;

    before(function(){
        BIN_SCOPE = (new DataScope("bin")).setPpts(DataScopePpts.PATH, _path_.join(TEST_WS,TEST_APP,'apk'));
    });

    beforeEach(function() {

    });

    afterEach(function() {
       // console.log.restore();
    });
    
    describe('new', function() {
        console.log(BIN_SCOPE.getName(),_path_.join(TEST_WS,TEST_APP,'apk','lib','armeabi','libcrackmelib.so'));
        let m = new ModelFile({
            path: _path_.join(TEST_WS,TEST_APP,'apk','lib','armeabi','libcrackmelib.so'),
            type: 'ELF',
            name: 'libcrackmelib.so',
            scope: BIN_SCOPE
        });

        it('has UID autogenerated', function () {
            expect(m.getUID()).to.equals(m.generateUID());
        });

        it('autoconf', function () {
            expect(m.path).to.equals(_path_.join(TEST_WS,TEST_APP,'apk','lib','armeabi','libcrackmelib.so'));
            expect(m.type).to.equals('ELF');
            expect(m.name).to.equals('libcrackmelib.so');
            expect(m.scope.getName()).to.equals("bin");
        });
    });

    describe('properties', function() {

        it('configuration pat', function () {
            

           // expect(p.nofrida).to.equals(0);
        });
    });
});