import InspectorFactory, {FlattenTagCategoryOptions} from "../../src/InspectorFactory.js";
import {INSPECTOR_TYPE} from "../../src/Inspector.js";
import * as Log from "../../src/Logger.js";


// Regex match hash to hash function
// Source from Psypanda - HashId https://github.com/psypanda/hashID/blob/master/hashid.py
// Source Hashcat hashes database example: https://hashcat.net/wiki/doku.php?id=example_hashes
const HASH_TAG_CATEGORY_NAME = "crypto.hash";
let Logger:Log.Logger = Log.newLogger() as Log.Logger;

var hashIdentifierTags: FlattenTagCategoryOptions[] = [
    {
        name: HASH_TAG_CATEGORY_NAME,
        _tagsOptions: [
            {name:"CRC-16", label:"CRC-16", extra: {hashcat:undefined, john:undefined, extended:false}},
            {name:"CRC-16-CCITT", label:"CRC-16-CCITT", extra: {hashcat:undefined, john:undefined, extended:false}},
            {name:"Adler-32", label:"Adler-32", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"CRC-32B", label:"CRC-32B", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"FCS-32", label:"FCS-32", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"GHash-32-3", label:"GHash-32-3", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"GHash-32-5", label:"GHash-32-5", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"FNV-132", label:"FNV-132", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Fletcher-32", label:"Fletcher-32", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Joaat", label:"Joaat", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"ELF-32", label:"ELF-32", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"XOR-32", label:"XOR-32", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"CRC-24", label:"CRC-24", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"CRC-32", label:"CRC-32", extra: {hashcat: undefined, john: 'crc32', extended: false}},
            {name:"Eggdrop IRC Bot", label:"Eggdrop IRC Bot", extra: {hashcat: undefined, john: 'bfegg', extended: false}},
            {name:"DES(Unix)", label:"DES(Unix)", extra: {hashcat: 1500, john: 'descrypt', extended: false}},
            {name:"Traditional DES", label:"Traditional DES", extra: {hashcat: 1500, john: 'descrypt', extended: false}},
            {name:"DEScrypt", label:"DEScrypt", extra: {hashcat: 1500, john: 'descrypt', extended: false}},
            {name:"MySQL323", label:"MySQL323", extra: {hashcat: 200, john: 'mysql', extended: false}},
            {name:"DES(Oracle)", label:"DES(Oracle)", extra: {hashcat: 3100, john: undefined, extended: false}},
            {name:"Half MD5", label:"Half MD5", extra: {hashcat: 5100, john: undefined, extended: false}},
            {name:"Oracle 7-10g", label:"Oracle 7-10g", extra: {hashcat: 3100, john: undefined, extended: false}},
            {name:"FNV-164", label:"FNV-164", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"CRC-64", label:"CRC-64", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Cisco-PIX(MD5)", label:"Cisco-PIX(MD5)", extra: {hashcat: 2400, john: 'pix-md5', extended: false}},
            {name:"Lotus Notes/Domino 6", label:"Lotus Notes/Domino 6", extra: {hashcat: 8700, john: 'dominosec', extended: false}},
            {name:"BSDi Crypt", label:"BSDi Crypt", extra: {hashcat: undefined, john: 'bsdicrypt', extended: false}},
            {name:"CRC-96(ZIP)", label:"CRC-96(ZIP)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Crypt16", label:"Crypt16", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"MD2", label:"MD2", extra: {hashcat: undefined, john: 'md2', extended: false}},
            {name:"MD5", label:"MD5", extra: {hashcat: 0, john: 'raw-md5', extended: false}},
            {name:"MD4", label:"MD4", extra: {hashcat: 900, john: 'raw-md4', extended: false}},
            {name:"Double MD5", label:"Double MD5", extra: {hashcat: 2600, john: undefined, extended: false}},
            {name:"LM", label:"LM", extra: {hashcat: 3000, john: 'lm', extended: false}},
            {name:"RIPEMD-128", label:"RIPEMD-128", extra: {hashcat: undefined, john: 'ripemd-128', extended: false}},
            {name:"Haval-128", label:"Haval-128", extra: {hashcat: undefined, john: 'haval-128-4', extended: false}},
            {name:"Tiger-128", label:"Tiger-128", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Skein-256(128)", label:"Skein-256(128)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Skein-512(128)", label:"Skein-512(128)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Lotus Notes/Domino 5", label:"Lotus Notes/Domino 5", extra: {hashcat: 8600, john: 'lotus5', extended: false}},
            {name:"Skype", label:"Skype", extra: {hashcat: 23, john: undefined, extended: false}},
            {name:"ZipMonster", label:"ZipMonster", extra: {hashcat: undefined, john: undefined, extended: true}},
            {name:"PrestaShop", label:"PrestaShop", extra: {hashcat: 11000, john: undefined, extended: true}},
            {name:"md5(md5(md5($pass)))", label:"md5(md5(md5($pass)))", extra: {hashcat: 3500, john: undefined, extended: true}},
            {name:"md5(strtoupper(md5($pass)))", label:"md5(strtoupper(md5($pass)))", extra: {hashcat: 4300, john: undefined, extended: true}},
            {name:"md5(sha1($pass))", label:"md5(sha1($pass))", extra: {hashcat: 4400, john: undefined, extended: true}},
            {name:"md5($pass_$salt)", label:"md5($pass.$salt)", extra: {hashcat: 10, john: undefined, extended: true}},
            {name:"md5($salt_$pass)", label:"md5($salt.$pass)", extra: {hashcat: 20, john: undefined, extended: true}},
            {name:"md5(unicode($pass)_$salt)", label:"md5(unicode($pass).$salt)", extra: {hashcat: 30, john: undefined, extended: true}},
            {name:"md5($salt_unicode($pass))", label:"md5($salt.unicode($pass))", extra: {hashcat: 40, john: undefined, extended: true}},
            {name:"HMAC-MD5 (key = $pass)", label:"HMAC-MD5 (key = $pass)", extra: {hashcat: 50, john: 'hmac-md5', extended: true}},
            {name:"HMAC-MD5 (key = $salt)", label:"HMAC-MD5 (key = $salt)", extra: {hashcat: 60, john: 'hmac-md5', extended: true}},
            {name:"md5(md5($salt)_$pass)", label:"md5(md5($salt).$pass)", extra: {hashcat: 3610, john: undefined, extended: true}},
            {name:"md5($salt_md5($pass))", label:"md5($salt.md5($pass))", extra: {hashcat: 3710, john: undefined, extended: true}},
            {name:"md5($pass_md5($salt))", label:"md5($pass.md5($salt))", extra: {hashcat: 3720, john: undefined, extended: true}},
            {name:"md5($salt_$pass_$salt)", label:"md5($salt.$pass.$salt)", extra: {hashcat: 3810, john: undefined, extended: true}},
            {name:"md5(md5($pass)_md5($salt))", label:"md5(md5($pass).md5($salt))", extra: {hashcat: 3910, john: undefined, extended: true}},
            {name:"md5($salt_md5($salt_$pass))", label:"md5($salt.md5($salt.$pass))", extra: {hashcat: 4010, john: undefined, extended: true}},
            {name:"md5($salt_md5($pass_$salt))", label:"md5($salt.md5($pass.$salt))", extra: {hashcat: 4110, john: undefined, extended: true}},
            {name:"md5($username_0_$pass)", label:"md5($username.0.$pass)", extra: {hashcat: 4210, john: undefined, extended: true}},
            {name:"Snefru-128", label:"Snefru-128", extra: {hashcat: undefined, john: 'snefru-128', extended: false}},
            {name:"NTLM", label:"NTLM", extra: {hashcat: 1000, john: 'nt', extended: false}},
            {name:"Domain Cached Credentials", label:"Domain Cached Credentials", extra: {hashcat: 1100, john: 'mscach', extended: false}},
            {name:"Domain Cached Credentials 2", label:"Domain Cached Credentials 2", extra: {hashcat: 2100, john: 'mscach2', extended: false}},
            {name:"SHA-1(Base64)", label:"SHA-1(Base64)", extra: {hashcat: 101, john: 'nsldap', extended: false}},
            {name:"Netscape LDAP SHA", label:"Netscape LDAP SHA", extra: {hashcat: 101, john: 'nsldap', extended: false}},
            {name:"MD5 Crypt", label:"MD5 Crypt", extra: {hashcat: 500, john: 'md5crypt', extended: false}},
            {name:"Cisco-IOS(MD5)", label:"Cisco-IOS(MD5)", extra: {hashcat: 500, john: 'md5crypt', extended: false}},
            {name:"FreeBSD MD5", label:"FreeBSD MD5", extra: {hashcat: 500, john: 'md5crypt', extended: false}},
            {name:"Lineage II C4", label:"Lineage II C4", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"phpBB v3_x", label:"phpBB v3.x", extra: {hashcat: 400, john: 'phpass', extended: false}},
            {name:"Wordpress v2_6_0/2_6_1", label:"Wordpress v2.6.0/2.6.1", extra: {hashcat: 400, john: 'phpass', extended: false}},
            {name:"PHPass' Portable Hash", label:"PHPass' Portable Hash", extra: {hashcat: 400, john: 'phpass', extended: false}},
            {name:"Wordpress >= v2_6_2", label:"Wordpress >= v2.6.2", extra: {hashcat: 400, john: 'phpass', extended: false}},
            {name:"Joomla >= v2_5_18", label:"Joomla >= v2.5.18", extra: {hashcat: 400, john: 'phpass', extended: false}},
            {name:"PHPass' Portable Hash", label:"PHPass' Portable Hash", extra: {hashcat: 400, john: 'phpass', extended: false}},
            {name:"osCommerce", label:"osCommerce", extra: {hashcat: 21, john: undefined, extended: false}},
            {name:"xt:Commerce", label:"xt:Commerce", extra: {hashcat: 21, john: undefined, extended: false}},
            {name:"MD5(APR)", label:"MD5(APR)", extra: {hashcat: 1600, john: undefined, extended: false}},
            {name:"Apache MD5", label:"Apache MD5", extra: {hashcat: 1600, john: undefined, extended: false}},
            {name:"md5apr1", label:"md5apr1", extra: {hashcat: 1600, john: undefined, extended: true}},
            {name:"AIX(smd5)", label:"AIX(smd5)", extra: {hashcat: 6300, john: 'aix-smd5', extended: false}},
            {name:"WebEdition CMS", label:"WebEdition CMS", extra: {hashcat: 3721, john: undefined, extended: false}},
            {name:"IP_Board >= v2+", label:"IP.Board >= v2+", extra: {hashcat: 2811, john: undefined, extended: false}},
            {name:"MyBB >= v1_2+", label:"MyBB >= v1.2+", extra: {hashcat: 2811, john: undefined, extended: false}},
            {name:"CryptoCurrency(Adress)", label:"CryptoCurrency(Adress)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"SHA-1", label:"SHA-1", extra: {hashcat: 100, john: 'raw-sha1', extended: false}},
            {name:"Double SHA-1", label:"Double SHA-1", extra: {hashcat: 4500, john: undefined, extended: false}},
            {name:"RIPEMD-160", label:"RIPEMD-160", extra: {hashcat: 6000, john: 'ripemd-160', extended: false}},
            {name:"Haval-160", label:"Haval-160", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Tiger-160", label:"Tiger-160", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"HAS-160", label:"HAS-160", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"LinkedIn", label:"LinkedIn", extra: {hashcat: 190, john: 'raw-sha1-linkedin', extended: false}},
            {name:"Skein-256(160)", label:"Skein-256(160)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Skein-512(160)", label:"Skein-512(160)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"MangosWeb Enhanced CMS", label:"MangosWeb Enhanced CMS", extra: {hashcat: undefined, john: undefined, extended: true}},
            {name:"sha1(sha1(sha1($pass)))", label:"sha1(sha1(sha1($pass)))", extra: {hashcat: 4600, john: undefined, extended: true}},
            {name:"sha1(md5($pass))", label:"sha1(md5($pass))", extra: {hashcat: 4700, john: undefined, extended: true}},
            {name:"sha1($pass_$salt)", label:"sha1($pass.$salt)", extra: {hashcat: 110, john: undefined, extended: true}},
            {name:"sha1($salt_$pass)", label:"sha1($salt.$pass)", extra: {hashcat: 120, john: undefined, extended: true}},
            {name:"sha1(unicode($pass)_$salt)", label:"sha1(unicode($pass).$salt)", extra: {hashcat: 130, john: undefined, extended: true}},
            {name:"sha1($salt_unicode($pass))", label:"sha1($salt.unicode($pass))", extra: {hashcat: 140, john: undefined, extended: true}},
            {name:"HMAC-SHA1 (key = $pass)", label:"HMAC-SHA1 (key = $pass)", extra: {hashcat: 150, john: 'hmac-sha1', extended: true}},
            {name:"HMAC-SHA1 (key = $salt)", label:"HMAC-SHA1 (key = $salt)", extra: {hashcat: 160, john: 'hmac-sha1', extended: true}},
            {name:"sha1($salt_$pass_$salt)", label:"sha1($salt.$pass.$salt)", extra: {hashcat: 4710, john: undefined, extended: true}},
            {name:"MySQL5_x", label:"MySQL5.x", extra: {hashcat: 300, john: 'mysql-sha1', extended: false}},
            {name:"MySQL4_1", label:"MySQL4.1", extra: {hashcat: 300, john: 'mysql-sha1', extended: false}},
            {name:"Cisco-IOS(SHA-256)", label:"Cisco-IOS(SHA-256)", extra: {hashcat: 5700, john: undefined, extended: false}},
            {name:"SSHA-1(Base64)", label:"SSHA-1(Base64)", extra: {hashcat: 111, john: 'nsldaps', extended: false}},
            {name:"Netscape LDAP SSHA", label:"Netscape LDAP SSHA", extra: {hashcat: 111, john: 'nsldaps', extended: false}},
            {name:"nsldaps", label:"nsldaps", extra: {hashcat: 111, john: 'nsldaps', extended: true}},
            {name:"Fortigate(FortiOS)", label:"Fortigate(FortiOS)", extra: {hashcat: 7000, john: 'fortigate', extended: false}},
            {name:"Haval-192", label:"Haval-192", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Tiger-192", label:"Tiger-192", extra: {hashcat: undefined, john: 'tiger', extended: false}},
            {name:"SHA-1(Oracle)", label:"SHA-1(Oracle)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"OSX v10_4", label:"OSX v10.4", extra: {hashcat: 122, john: 'xsha', extended: false}},
            {name:"OSX v10_5", label:"OSX v10.5", extra: {hashcat: 122, john: 'xsha', extended: false}},
            {name:"OSX v10_6", label:"OSX v10.6", extra: {hashcat: 122, john: 'xsha', extended: false}},
            {name:"Palshop CMS", label:"Palshop CMS", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"CryptoCurrency(PrivateKey)", label:"CryptoCurrency(PrivateKey)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"AIX(ssha1)", label:"AIX(ssha1)", extra: {hashcat: 6700, john: 'aix-ssha1', extended: false}},
            {name:"MSSQL(2005)", label:"MSSQL(2005)", extra: {hashcat: 132, john: 'mssql05', extended: false}},
            {name:"MSSQL(2008)", label:"MSSQL(2008)", extra: {hashcat: 132, john: 'mssql05', extended: false}},
            {name:"Sun MD5 Crypt", label:"Sun MD5 Crypt", extra: {hashcat: 3300, john: 'sunmd5', extended: false}},
            {name:"SHA-224", label:"SHA-224", extra: {hashcat: undefined, john: 'raw-sha224', extended: false}},
            {name:"Haval-224", label:"Haval-224", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"SHA3-224", label:"SHA3-224", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Skein-256(224)", label:"Skein-256(224)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Skein-512(224)", label:"Skein-512(224)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Blowfish(OpenBSD)", label:"Blowfish(OpenBSD)", extra: {hashcat: 3200, john: 'bcrypt', extended: false}},
            {name:"Woltlab Burning Board 4_x", label:"Woltlab Burning Board 4.x", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"bcrypt", label:"bcrypt", extra: {hashcat: 3200, john: 'bcrypt', extended: false}},
            {name:"Android PIN", label:"Android PIN", extra: {hashcat: 5800, john: undefined, extended: false}},
            {name:"Oracle 11g/12c", label:"Oracle 11g/12c", extra: {hashcat: 112, john: 'oracle11', extended: false}},
            {name:"bcrypt(SHA-256)", label:"bcrypt(SHA-256)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"vBulletin < v3_8_5", label:"vBulletin < v3.8.5", extra: {hashcat: 2611, john: undefined, extended: false}},
            {name:"vBulletin >= v3_8_5", label:"vBulletin >= v3.8.5", extra: {hashcat: 2711, john: undefined, extended: false}},
            {name:"Snefru-256", label:"Snefru-256", extra: {hashcat: undefined, john: 'snefru-256', extended: false}},
            {name:"SHA-256", label:"SHA-256", extra: {hashcat: 1400, john: 'raw-sha256', extended: false}},
            {name:"RIPEMD-256", label:"RIPEMD-256", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Haval-256", label:"Haval-256", extra: {hashcat: undefined, john: 'haval-256-3', extended: false}},
            {name:"GOST R 34_11-94", label:"GOST R 34.11-94", extra: {hashcat: 6900, john: 'gost', extended: false}},
            {name:"GOST CryptoPro S-Box", label:"GOST CryptoPro S-Box", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"SHA3-256", label:"SHA3-256", extra: {hashcat: 5000, john: 'raw-keccak-256', extended: false}},
            {name:"Skein-256", label:"Skein-256", extra: {hashcat: undefined, john: 'skein-256', extended: false}},
            {name:"Skein-512(256)", label:"Skein-512(256)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Ventrilo", label:"Ventrilo", extra: {hashcat: undefined, john: undefined, extended: true}},
            {name:"sha256($pass_$salt)", label:"sha256($pass.$salt)", extra: {hashcat: 1410, john: undefined, extended: true}},
            {name:"sha256($salt_$pass)", label:"sha256($salt.$pass)", extra: {hashcat: 1420, john: undefined, extended: true}},
            {name:"sha256(unicode($pass)_$salt)", label:"sha256(unicode($pass).$salt)", extra: {hashcat: 1430, john: undefined, extended: true}},
            {name:"sha256($salt_unicode($pass))", label:"sha256($salt.unicode($pass))", extra: {hashcat: 1440, john: undefined, extended: true}},
            {name:"HMAC-SHA256 (key = $pass)", label:"HMAC-SHA256 (key = $pass)", extra: {hashcat: 1450, john: 'hmac-sha256', extended: true}},
            {name:"HMAC-SHA256 (key = $salt)", label:"HMAC-SHA256 (key = $salt)", extra: {hashcat: 1460, john: 'hmac-sha256', extended: true}},
            {name:"Joomla < v2_5_18", label:"Joomla < v2.5.18", extra: {hashcat: 11, john: undefined, extended: false}},
            {name:"SAM(LM_Hash:NT_Hash)", label:"SAM(LM_Hash:NT_Hash)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"MD5(Chap)", label:"MD5(Chap)", extra: {hashcat: 4800, john: 'chap', extended: false}},
            {name:"iSCSI CHAP Authentication", label:"iSCSI CHAP Authentication", extra: {hashcat: 4800, john: 'chap', extended: false}},
            {name:"EPiServer 6_x < v4", label:"EPiServer 6.x < v4", extra: {hashcat: 141, john: 'episerver', extended: false}},
            {name:"AIX(ssha256)", label:"AIX(ssha256)", extra: {hashcat: 6400, john: 'aix-ssha256', extended: false}},
            {name:"RIPEMD-320", label:"RIPEMD-320", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"EPiServer 6_x >= v4", label:"EPiServer 6.x >= v4", extra: {hashcat: 1441, john: 'episerver', extended: false}},
            {name:"MSSQL(2000)", label:"MSSQL(2000)", extra: {hashcat: 131, john: 'mssql', extended: false}},
            {name:"SHA-384", label:"SHA-384", extra: {hashcat: 10800, john: 'raw-sha384', extended: false}},
            {name:"SHA3-384", label:"SHA3-384", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Skein-512(384)", label:"Skein-512(384)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Skein-1024(384)", label:"Skein-1024(384)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"SSHA-512(Base64)", label:"SSHA-512(Base64)", extra: {hashcat: 1711, john: 'ssha512', extended: false}},
            {name:"LDAP(SSHA-512)", label:"LDAP(SSHA-512)", extra: {hashcat: 1711, john: 'ssha512', extended: false}},
            {name:"AIX(ssha512)", label:"AIX(ssha512)", extra: {hashcat: 6500, john: 'aix-ssha512', extended: false}},
            {name:"SHA-512", label:"SHA-512", extra: {hashcat: 1700, john: 'raw-sha512', extended: false}},
            {name:"Whirlpool", label:"Whirlpool", extra: {hashcat: 6100, john: 'whirlpool', extended: false}},
            {name:"Salsa10", label:"Salsa10", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Salsa20", label:"Salsa20", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"SHA3-512", label:"SHA3-512", extra: {hashcat: undefined, john: 'raw-keccak', extended: false}},
            {name:"Skein-512", label:"Skein-512", extra: {hashcat: undefined, john: 'skein-512', extended: false}},
            {name:"Skein-1024(512)", label:"Skein-1024(512)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"sha512($pass_$salt)", label:"sha512($pass.$salt)", extra: {hashcat: 1710, john: undefined, extended: true}},
            {name:"sha512($salt_$pass)", label:"sha512($salt.$pass)", extra: {hashcat: 1720, john: undefined, extended: true}},
            {name:"sha512(unicode($pass)_$salt)", label:"sha512(unicode($pass).$salt)", extra: {hashcat: 1730, john: undefined, extended: true}},
            {name:"sha512($salt_unicode($pass))", label:"sha512($salt.unicode($pass))", extra: {hashcat: 1740, john: undefined, extended: true}},
            {name:"HMAC-SHA512 (key = $pass)", label:"HMAC-SHA512 (key = $pass)", extra: {hashcat: 1750, john: 'hmac-sha512', extended: true}},
            {name:"HMAC-SHA512 (key = $salt)", label:"HMAC-SHA512 (key = $salt)", extra: {hashcat: 1760, john: 'hmac-sha512', extended: true}},
            {name:"OSX v10_7", label:"OSX v10.7", extra: {hashcat: 1722, john: 'xsha512', extended: false}},
            {name:"MSSQL(2012)", label:"MSSQL(2012)", extra: {hashcat: 1731, john: 'msql12', extended: false}},
            {name:"MSSQL(2014)", label:"MSSQL(2014)", extra: {hashcat: 1731, john: 'msql12', extended: false}},
            {name:"OSX v10_8", label:"OSX v10.8", extra: {hashcat: 7100, john: 'pbkdf2-hmac-sha512', extended: false}},
            {name:"OSX v10_9", label:"OSX v10.9", extra: {hashcat: 7100, john: 'pbkdf2-hmac-sha512', extended: false}},
            {name:"Skein-1024", label:"Skein-1024", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"GRUB 2", label:"GRUB 2", extra: {hashcat: 7200, john: undefined, extended: false}},
            {name:"Django(SHA-1)", label:"Django(SHA-1)", extra: {hashcat: 124, john: undefined, extended: false}},
            {name:"Citrix Netscaler", label:"Citrix Netscaler", extra: {hashcat: 8100, john: 'citrix_ns10', extended: false}},
            {name:"Drupal > v7_x", label:"Drupal > v7.x", extra: {hashcat: 7900, john: 'drupal7', extended: false}},
            {name:"SHA-256 Crypt", label:"SHA-256 Crypt", extra: {hashcat: 7400, john: 'sha256crypt', extended: false}},
            {name:"Sybase ASE", label:"Sybase ASE", extra: {hashcat: 8000, john: 'sybasease', extended: false}},
            {name:"SHA-512 Crypt", label:"SHA-512 Crypt", extra: {hashcat: 1800, john: 'sha512crypt', extended: false}},
            {name:"Minecraft(AuthMe Reloaded)", label:"Minecraft(AuthMe Reloaded)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Django(SHA-256)", label:"Django(SHA-256)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Django(SHA-384)", label:"Django(SHA-384)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Clavister Secure Gateway", label:"Clavister Secure Gateway", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Cisco VPN Client(PCF-File)", label:"Cisco VPN Client(PCF-File)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Microsoft MSTSC(RDP-File)", label:"Microsoft MSTSC(RDP-File)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"NetNTLMv1-VANILLA / NetNTLMv1+ESS", label:"NetNTLMv1-VANILLA / NetNTLMv1+ESS", extra: {hashcat: 5500, john: 'netntlm', extended: false}},
            {name:"NetNTLMv2", label:"NetNTLMv2", extra: {hashcat: 5600, john: 'netntlmv2', extended: false}},
            {name:"Kerberos 5 AS-REQ Pre-Auth", label:"Kerberos 5 AS-REQ Pre-Auth", extra: {hashcat: 7500, john: 'krb5pa-md5', extended: false}},
            {name:"SCRAM Hash", label:"SCRAM Hash", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Redmine Project Management Web App", label:"Redmine Project Management Web App", extra: {hashcat: 7600, john: undefined, extended: false}},
            {name:"SAP CODVN B (BCODE)", label:"SAP CODVN B (BCODE)", extra: {hashcat: 7700, john: 'sapb', extended: false}},
            {name:"SAP CODVN F/G (PASSCODE)", label:"SAP CODVN F/G (PASSCODE)", extra: {hashcat: 7800, john: 'sapg', extended: false}},
            {name:"Juniper Netscreen/SSG(ScreenOS)", label:"Juniper Netscreen/SSG(ScreenOS)", extra: {hashcat: 22, john: 'md5ns', extended: false}},
            {name:"EPi", label:"EPi", extra: {hashcat: 123, john: undefined, extended: false}},
            {name:"SMF >= v1_1", label:"SMF >= v1.1", extra: {hashcat: 121, john: undefined, extended: false}},
            {name:"Woltlab Burning Board 3_x", label:"Woltlab Burning Board 3.x", extra: {hashcat: 8400, john: 'wbb3', extended: false}},
            {name:"IPMI2 RAKP HMAC-SHA1", label:"IPMI2 RAKP HMAC-SHA1", extra: {hashcat: 7300, john: undefined, extended: false}},
            {name:"Lastpass", label:"Lastpass", extra: {hashcat: 6800, john: undefined, extended: false}},
            {name:"Cisco-ASA(MD5)", label:"Cisco-ASA(MD5)", extra: {hashcat: 2410, john: 'asa-md5', extended: false}},
            {name:"VNC", label:"VNC", extra: {hashcat: undefined, john: 'vnc', extended: false}},
            {name:"DNSSEC(NSEC3)", label:"DNSSEC(NSEC3)", extra: {hashcat: 8300, john: undefined, extended: false}},
            {name:"RACF", label:"RACF", extra: {hashcat: 8500, john: 'racf', extended: false}},
            {name:"NTHash(FreeBSD Variant)", label:"NTHash(FreeBSD Variant)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"SHA-1 Crypt", label:"SHA-1 Crypt", extra: {hashcat: undefined, john: 'sha1crypt', extended: false}},
            {name:"hMailServer", label:"hMailServer", extra: {hashcat: 1421, john: 'hmailserver', extended: false}},
            {name:"MediaWiki", label:"MediaWiki", extra: {hashcat: 3711, john: 'mediawiki', extended: false}},
            {name:"Minecraft(xAuth)", label:"Minecraft(xAuth)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PBKDF2-SHA1(Generic)", label:"PBKDF2-SHA1(Generic)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PBKDF2-SHA256(Generic)", label:"PBKDF2-SHA256(Generic)", extra: {hashcat: undefined, john: 'pbkdf2-hmac-sha256', extended: false}},
            {name:"PBKDF2-SHA512(Generic)", label:"PBKDF2-SHA512(Generic)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PBKDF2(Cryptacular)", label:"PBKDF2(Cryptacular)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PBKDF2(Dwayne Litzenberger)", label:"PBKDF2(Dwayne Litzenberger)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Fairly Secure Hashed Password", label:"Fairly Secure Hashed Password", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PHPS", label:"PHPS", extra: {hashcat: 2612, john: 'phps', extended: false}},
            {name:"1Password(Agile Keychain)", label:"1Password(Agile Keychain)", extra: {hashcat: 6600, john: undefined, extended: false}},
            {name:"1Password(Cloud Keychain)", label:"1Password(Cloud Keychain)", extra: {hashcat: 8200, john: undefined, extended: false}},
            {name:"IKE-PSK MD5", label:"IKE-PSK MD5", extra: {hashcat: 5300, john: undefined, extended: false}},
            {name:"IKE-PSK SHA1", label:"IKE-PSK SHA1", extra: {hashcat: 5400, john: undefined, extended: false}},
            {name:"PeopleSoft", label:"PeopleSoft", extra: {hashcat: 133, john: undefined, extended: false}},
            {name:"Django(DES Crypt Wrapper)", label:"Django(DES Crypt Wrapper)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Django(PBKDF2-HMAC-SHA256)", label:"Django(PBKDF2-HMAC-SHA256)", extra: {hashcat: 10000, john: 'django', extended: false}},
            {name:"Django(PBKDF2-HMAC-SHA1)", label:"Django(PBKDF2-HMAC-SHA1)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Django(bcrypt)", label:"Django(bcrypt)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Django(MD5)", label:"Django(MD5)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PBKDF2(Atlassian)", label:"PBKDF2(Atlassian)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PostgreSQL MD5", label:"PostgreSQL MD5", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Lotus Notes/Domino 8", label:"Lotus Notes/Domino 8", extra: {hashcat: 9100, john: undefined, extended: false}},
            {name:"scrypt", label:"scrypt", extra: {hashcat: 8900, john: undefined, extended: false}},
            {name:"Cisco Type 8", label:"Cisco Type 8", extra: {hashcat: 9200, john: 'cisco8', extended: false}},
            {name:"Cisco Type 9", label:"Cisco Type 9", extra: {hashcat: 9300, john: 'cisco9', extended: false}},
            {name:"Microsoft Office 2007", label:"Microsoft Office 2007", extra: {hashcat: 9400, john: 'office', extended: false}},
            {name:"Microsoft Office 2010", label:"Microsoft Office 2010", extra: {hashcat: 9500, john: undefined, extended: false}},
            {name:"Microsoft Office 2013", label:"Microsoft Office 2013", extra: {hashcat: 9600, john: undefined, extended: false}},
            {name:"Android FDE <= 4_3", label:"Android FDE <= 4.3", extra: {hashcat: 8800, john: 'fde', extended: false}},
            {name:"Microsoft Office <= 2003 (MD5+RC4)", label:"Microsoft Office <= 2003 (MD5+RC4)", extra: {hashcat: 9700, john: 'oldoffice', extended: false}},
            {name:"Microsoft Office <= 2003 (MD5+RC4) collider-mode #1", label:"Microsoft Office <= 2003 (MD5+RC4) collider-mode #1", extra: {hashcat: 9710, john: 'oldoffice', extended: false}},
            {name:"Microsoft Office <= 2003 (MD5+RC4) collider-mode #2", label:"Microsoft Office <= 2003 (MD5+RC4) collider-mode #2", extra: {hashcat: 9720, john: 'oldoffice', extended: false}},
            {name:"Microsoft Office <= 2003 (SHA1+RC4)", label:"Microsoft Office <= 2003 (SHA1+RC4)", extra: {hashcat: 9800, john: undefined, extended: false}},
            {name:"Microsoft Office <= 2003 (SHA1+RC4) collider-mode #1", label:"Microsoft Office <= 2003 (SHA1+RC4) collider-mode #1", extra: {hashcat: 9810, john: undefined, extended: false}},
            {name:"Microsoft Office <= 2003 (SHA1+RC4) collider-mode #2", label:"Microsoft Office <= 2003 (SHA1+RC4) collider-mode #2", extra: {hashcat: 9820, john: undefined, extended: false}},
            {name:"RAdmin v2_x", label:"RAdmin v2.x", extra: {hashcat: 9900, john: 'radmin', extended: false}},
            {name:"SAP CODVN H (PWDSALTEDHASH) iSSHA-1", label:"SAP CODVN H (PWDSALTEDHASH) iSSHA-1", extra: {hashcat: 10300, john: 'saph', extended: false}},
            {name:"CRAM-MD5", label:"CRAM-MD5", extra: {hashcat: 10200, john: undefined, extended: false}},
            {name:"SipHash", label:"SipHash", extra: {hashcat: 10100, john: undefined, extended: false}},
            {name:"Cisco Type 7", label:"Cisco Type 7", extra: {hashcat: undefined, john: undefined, extended: true}},
            {name:"BigCrypt", label:"BigCrypt", extra: {hashcat: undefined, john: 'bigcrypt', extended: true}},
            {name:"Cisco Type 4", label:"Cisco Type 4", extra: {hashcat: undefined, john: 'cisco4', extended: false}},
            {name:"Django(bcrypt-SHA256)", label:"Django(bcrypt-SHA256)", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PostgreSQL Challenge-Response Authentication (MD5)", label:"PostgreSQL Challenge-Response Authentication (MD5)", extra: {hashcat: 11100, john: 'postgres', extended: false}},
            {name:"Siemens-S7", label:"Siemens-S7", extra: {hashcat: undefined, john: 'siemens-s7', extended: false}},
            {name:"Microsoft Outlook PST", label:"Microsoft Outlook PST", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"PBKDF2-HMAC-SHA256(PHP)", label:"PBKDF2-HMAC-SHA256(PHP)", extra: {hashcat: 10900, john: undefined, extended: false}},
            {name:"Dahua", label:"Dahua", extra: {hashcat: undefined, john: 'dahua', extended: false}},
            {name:"MySQL Challenge-Response Authentication (SHA1)", label:"MySQL Challenge-Response Authentication (SHA1)", extra: {hashcat: 11200, john: undefined, extended: false}},
            {name:"PDF 1_4 - 1_6 (Acrobat 5 - 8)", label:"PDF 1.4 - 1.6 (Acrobat 5 - 8)", extra: {hashcat: 10500, john: 'pdf', extended: false}},
            {name:"Bitcoin P2PKH Base58Check", label:"Bitcoin P2PKH Base58Check", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Bitcoin P2SH Base58Check", label:"Bitcoin P2SH Base58Check", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Bitcoin P2WPKH SegWit Bech32", label:"Bitcoin P2WPKH SegWit Bech32", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Bitcoin P2TR SegWit Bech32", label:"Bitcoin P2TR SegWit Bech32", extra: {hashcat: undefined, john: undefined, extended: false}},
            {name:"Bitcoin Test address", label:"Bitcoin Test address", extra: {hashcat: undefined, john: undefined, extended: false}}
        ]
    }
];

// Add '.source' at each regex in order to stringify regexToHash.
var regexToHash = [
   // {regex: /^[a-f0-9]{4}$/.source, modes: ['CRC-16', 'CRC-16-CCITT', 'FCS-16']},
   // {regex: /^[A-F0-9]{4}$/.source, modes: ['CRC-16', 'CRC-16-CCITT', 'FCS-16']},
   // {regex: /^[a-f0-9]{8}$/.source, modes: ['Adler-32', 'CRC-32B', 'FCS-32', 'GHash-32-3', 'GHash-32-5', 'FNV-132', 'Fletcher-32', 'Joaat', 'ELF-32', 'XOR-32']},
   // {regex: /^[A-F0-9]{8}$/.source, modes: ['Adler-32', 'CRC-32B', 'FCS-32', 'GHash-32-3', 'GHash-32-5', 'FNV-132', 'Fletcher-32', 'Joaat', 'ELF-32', 'XOR-32']},
   // {regex: /^[a-f0-9]{6}$/.source, modes: ['CRC-24']},
   // {regex: /^[A-F0-9]{6}$/.source, modes: ['CRC-24']},
    {regex: /^(\$crc32\$[a-f0-9]{8}.)?[a-f0-9]{8}$/.source, modes: ['CRC-32']},
    {regex: /^(\$crc32\$[A-F0-9]{8}.)?[A-F0-9]{8}$/.source, modes: ['CRC-32']},
   // {regex: /^[a-f0-9]{4,}$/.source, modes: ['Cisco Type 7']},
   // {regex: /^[A-F0-9]{4,}$/.source, modes: ['Cisco Type 7']},
   // {regex: /^\+[a-zA-Z0-9\/.]{12}$/.source, modes: ['Eggdrop IRC Bot']},
    {regex: /^(\$pst\$)?[a-f0-9]{8}$/.source, modes: ['Microsoft Outlook PST']},
    {regex: /^(\$pst\$)?[A-F0-9]{8}$/.source, modes: ['Microsoft Outlook PST']},
    {regex: /^(\$dahua\$)?[a-zA-Z0-9]{8}$/.source, modes: ['Dahua']},
    {regex: /^[a-zA-Z0-9\/+]{2}([a-zA-Z0-9\/+.]{11})+$/.source, modes: ['BigCrypt']},
    {regex: /^(\$cisco4\$)?[a-zA-Z0-9\/.]{43}$/.source, modes: ['Cisco Type 4']},
    {regex: /^(.+\$)?[a-zA-Z0-9\/.+]{30}(:.+)?$/.source, modes: ['Juniper Netscreen/SSG(ScreenOS)']},
    {regex: /^[a-zA-Z0-9\/.]{13}$/.source, modes: ['DES(Unix)', 'Traditional DES', 'DEScrypt']},
    {regex: /^[a-f0-9]{16}$/.source, modes: ['MySQL323', 'DES(Oracle)', 'Half MD5', 'Oracle 7-10g', 'FNV-164', 'CRC-64']},
    {regex: /^[A-F0-9]{16}$/.source, modes: ['MySQL323', 'DES(Oracle)', 'Half MD5', 'Oracle 7-10g', 'FNV-164', 'CRC-64']},
    {regex: /^[a-zA-Z0-9\/.]{16}$/.source, modes: ['Cisco-PIX(MD5)']},
    {regex: /^\([a-zA-Z0-9\/+]{20}\)$/.source, modes: ['Lotus Notes/Domino 6']},
    {regex: /^_[a-zA-Z0-9\/.]{19}$/.source, modes: ['BSDi Crypt']},
    {regex: /^[a-f0-9]{24}$/.source, modes: ['CRC-96(ZIP)']},
    {regex: /^[A-F0-9]{24}$/.source, modes: ['CRC-96(ZIP)']},
    {regex: /^[a-zA-Z0-9\/.]{24}$/.source, modes: ['Crypt16']},
    {regex: /^(\$md2\$)?[a-f0-9]{32}$/.source, modes: ['MD2']},
    {regex: /^(\$md2\$)?[A-F0-9]{32}$/.source, modes: ['MD2']},
    {regex: /^[a-f0-9]{32}(:.+)?$/.source, modes: ['MD5', 'MD4', 'Double MD5', 'LM', 'RIPEMD-128', 'Haval-128', 'Tiger-128', 'Skein-256(128)', 'Skein-512(128)', 'Lotus Notes/Domino 5', 'Skype', 'ZipMonster', 'PrestaShop', 'md5(md5(md5($pass)))', 'md5(strtoupper(md5($pass)))', 'md5(sha1($pass))', 'md5($pass_$salt)', 'md5($salt_$pass)', 'md5(unicode($pass)_$salt)', 'md5($salt_unicode($pass))', 'HMAC-MD5 (key = $pass)', 'HMAC-MD5 (key = $salt)', 'md5(md5($salt)_$pass)', 'md5($salt_md5($pass))', 'md5($pass_md5($salt))', 'md5($salt_$pass_$salt)', 'md5(md5($pass)_md5($salt))', 'md5($salt_md5($salt_$pass))', 'md5($salt_md5($pass_$salt))', 'md5($username_0_$pass)']},
    {regex: /^[A-F0-9]{32}(:.+)?$/.source, modes: ['MD5', 'MD4', 'Double MD5', 'LM', 'RIPEMD-128', 'Haval-128', 'Tiger-128', 'Skein-256(128)', 'Skein-512(128)', 'Lotus Notes/Domino 5', 'Skype', 'ZipMonster', 'PrestaShop', 'md5(md5(md5($pass)))', 'md5(strtoupper(md5($pass)))', 'md5(sha1($pass))', 'md5($pass_$salt)', 'md5($salt_$pass)', 'md5(unicode($pass)_$salt)', 'md5($salt_unicode($pass))', 'HMAC-MD5 (key = $pass)', 'HMAC-MD5 (key = $salt)', 'md5(md5($salt)_$pass)', 'md5($salt_md5($pass))', 'md5($pass_md5($salt))', 'md5($salt_$pass_$salt)', 'md5(md5($pass)_md5($salt))', 'md5($salt_md5($salt_$pass))', 'md5($salt_md5($pass_$salt))', 'md5($username_0_$pass)']},
    {regex: /^(\$snefru\$)?[a-f0-9]{32}$/.source, modes: ['Snefru-128']},
    {regex: /^(\$snefru\$)?[A-F0-9]{32}$/.source, modes: ['Snefru-128']},
    {regex: /^(\$NT\$)?[a-f0-9]{32}$/.source, modes: ['NTLM']},
    {regex: /^(\$NT\$)?[A-F0-9]{32}$/.source, modes: ['NTLM']},
    {regex: /^([^\\\/:*?"<>|]{1,20}:)?[a-f0-9]{32}(:[^\\\/:*?"<>|]{1,20})?$/.source, modes: ['Domain Cached Credentials']},
    {regex: /^([^\\\/:*?"<>|]{1,20}:)?[A-F0-9]{32}(:[^\\\/:*?"<>|]{1,20})?$/.source, modes: ['Domain Cached Credentials']},
    {regex: /^([^\\\/:*?"<>|]{1,20}:)?(\$DCC2\$10240#[^\\\/:*?"<>|]{1,20}#)?[a-f0-9]{32}$/.source, modes: ['Domain Cached Credentials 2']},
    {regex: /^([^\\\/:*?"<>|]{1,20}:)?(\$DCC2\$10240#[^\\\/:*?"<>|]{1,20}#)?[A-F0-9]{32}$/.source, modes: ['Domain Cached Credentials 2']},
    {regex: /^{SHA}[a-zA-Z0-9\/+]{27}=$/.source, modes: ['SHA-1(Base64)', 'Netscape LDAP SHA']},
    {regex: /^\$1\$[a-zA-Z0-9\/.]{0,8}\$[a-zA-Z0-9\/.]{22}(:.*)?$/.source, modes: ['MD5 Crypt', 'Cisco-IOS(MD5)', 'FreeBSD MD5']},
    {regex: /^0x[a-f0-9]{32}$/.source, modes: ['Lineage II C4']},
    {regex: /^0x[A-F0-9]{32}$/.source, modes: ['Lineage II C4']},
    {regex: /^\$H\$[a-zA-Z0-9\/.]{31}$/.source, modes: ['phpBB v3.x', 'Wordpress v2.6.0/2.6.1', "PHPass' Portable Hash"]},
    {regex: /^\$P\$[a-zA-Z0-9\/.]{31}$/.source, modes: ['Wordpress >= v2.6.2', 'Joomla >= v2.5.18', "PHPass' Portable Hash"]},
    {regex: /^[a-f0-9]{32}:[a-zA-Z0-9]{2}$/.source, modes: ['osCommerce', 'xt:Commerce']},
    {regex: /^[A-F0-9]{32}:[a-zA-Z0-9]{2}$/.source, modes: ['osCommerce', 'xt:Commerce']},
    {regex: /^\$apr1\$[a-zA-Z0-9\/.]{0,8}\$[a-zA-Z0-9\/.]{22}$/.source, modes: ['MD5(APR)', 'Apache MD5', 'md5apr1']},
    {regex: /^{smd5}[a-zA-Z0-9$\/.]{31}$/.source, modes: ['AIX(smd5)']},
    {regex: /^[a-f0-9]{32}:[a-f0-9]{32}$/.source, modes: ['WebEdition CMS']},
    {regex: /^[A-F0-9]{32}:[A-F0-9]{32}$/.source, modes: ['WebEdition CMS']},
    {regex: /^[a-f0-9]{32}:.{5}$/.source, modes: ['IP_Board >= v2+']},
    {regex: /^[A-F0-9]{32}:.{5}$/.source, modes: ['IP_Board >= v2+']},
    {regex: /^[a-f0-9]{32}:.{8}$/.source, modes: ['MyBB >= v1_2+']},
    {regex: /^[A-F0-9]{32}:.{8}$/.source, modes: ['MyBB >= v1_2+']},
    {regex: /^[a-zA-Z0-9]{34}$/.source, modes: ['CryptoCurrency(Adress)']},
    {regex: /^[a-f0-9]{40}(:.+)?$/.source, modes: ['SHA-1', 'Double SHA-1', 'RIPEMD-160', 'Haval-160', 'Tiger-160', 'HAS-160', 'LinkedIn', 'Skein-256(160)', 'Skein-512(160)', 'MangosWeb Enhanced CMS', 'sha1(sha1(sha1($pass)))', 'sha1(md5($pass))', 'sha1($pass_$salt)', 'sha1($salt_$pass)', 'sha1(unicode($pass)_$salt)', 'sha1($salt_unicode($pass))', 'HMAC-SHA1 (key = $pass)', 'HMAC-SHA1 (key = $salt)', 'sha1($salt_$pass_$salt)']},
    {regex: /^[A-F0-9]{40}(:.+)?$/.source, modes: ['SHA-1', 'Double SHA-1', 'RIPEMD-160', 'Haval-160', 'Tiger-160', 'HAS-160', 'LinkedIn', 'Skein-256(160)', 'Skein-512(160)', 'MangosWeb Enhanced CMS', 'sha1(sha1(sha1($pass)))', 'sha1(md5($pass))', 'sha1($pass_$salt)', 'sha1($salt_$pass)', 'sha1(unicode($pass)_$salt)', 'sha1($salt_unicode($pass))', 'HMAC-SHA1 (key = $pass)', 'HMAC-SHA1 (key = $salt)', 'sha1($salt_$pass_$salt)']},
    {regex: /^\*[a-f0-9]{40}$/.source, modes: ['MySQL5_x', 'MySQL4_1']},
    {regex: /^\*[A-F0-9]{40}$/.source, modes: ['MySQL5_x', 'MySQL4_1']},
    {regex: /^[a-zA-Z0-9]{43}$/.source, modes: ['Cisco-IOS(SHA-256)']},
    {regex: /^{SSHA}[a-zA-Z0-9\/+]{38}==$/.source, modes: ['SSHA-1(Base64)', 'Netscape LDAP SSHA', 'nsldaps']},
    {regex: /^[a-zA-Z0-9=]{47}$/.source, modes: ['Fortigate(FortiOS)']},
    {regex: /^[a-f0-9]{48}$/.source, modes: ['Haval-192', 'Tiger-192', 'SHA-1(Oracle)', 'OSX v10_4', 'OSX v10_5', 'OSX v10_6']},
    {regex: /^[A-F0-9]{48}$/.source, modes: ['Haval-192', 'Tiger-192', 'SHA-1(Oracle)', 'OSX v10_4', 'OSX v10_5', 'OSX v10_6']},
    {regex: /^[a-f0-9]{51}$/.source, modes: ['Palshop CMS']},
    {regex: /^[A-F0-9]{51}$/.source, modes: ['Palshop CMS']},
    {regex: /^[a-zA-Z0-9]{51}$/.source, modes: ['CryptoCurrency(PrivateKey)']},
    {regex: /^{ssha1}[0-9]{2}\$[a-zA-Z0-9$\/.]{44}$/.source, modes: ['AIX(ssha1)']},
    {regex: /^0x0100[a-f0-9]{48}$/.source, modes: ['MSSQL(2005)', 'MSSQL(2008)']},
    {regex: /^0x0100[A-F0-9]{48}$/.source, modes: ['MSSQL(2005)', 'MSSQL(2008)']},
    {regex: /^(\$md5,rounds=[0-9]+\$|\$md5\$rounds=[0-9]+\$|\$md5\$)[a-zA-Z0-9\/.]{0,16}(\$|\$\$)[a-zA-Z0-9\/.]{22}$/.source, modes: ['Sun MD5 Crypt']},
    {regex: /^[a-f0-9]{56}$/.source, modes: ['SHA-224', 'Haval-224', 'SHA3-224', 'Skein-256(224)', 'Skein-512(224)']},
    {regex: /^[A-F0-9]{56}$/.source, modes: ['SHA-224', 'Haval-224', 'SHA3-224', 'Skein-256(224)', 'Skein-512(224)']},
    {regex: /^(\$2[axy]|\$2)\$[0-9]{2}\$[a-zA-Z0-9\/.]{53}$/.source, modes: ['Blowfish(OpenBSD)', 'Woltlab Burning Board 4_x', 'bcrypt']},
    {regex: /^[a-f0-9]{40}:[a-f0-9]{16}$/.source, modes: ['Android PIN']},
    {regex: /^[A-F0-9]{40}:[A-F0-9]{16}$/.source, modes: ['Android PIN']},
    {regex: /^(S:)?[a-f0-9]{40}(:)?[a-f0-9]{20}$/.source, modes: ['Oracle 11g/12c']},
    {regex: /^(S:)?[A-F0-9]{40}(:)?[A-F0-9]{20}$/.source, modes: ['Oracle 11g/12c']},
    {regex: /^\$bcrypt-sha256\$(2[axy]|2),[0-9]+\$[a-zA-Z0-9\/.]{22}\$[a-zA-Z0-9\/.]{31}$/.source, modes: ['bcrypt(SHA-256)']},
    {regex: /^[a-f0-9]{32}:.{3}$/.source, modes: ['vBulletin < v3_8_5']},
    {regex: /^[A-F0-9]{32}:.{3}$/.source, modes: ['vBulletin < v3_8_5']},
    {regex: /^[a-f0-9]{32}:.{30}$/.source, modes: ['vBulletin >= v3_8_5']},
    {regex: /^[A-F0-9]{32}:.{30}$/.source, modes: ['vBulletin >= v3_8_5']},
    {regex: /^(\$snefru\$)?[a-f0-9]{64}$/.source, modes: ['Snefru-256']},
    {regex: /^(\$snefru\$)?[A-F0-9]{64}$/.source, modes: ['Snefru-256']},
    {regex: /^[a-f0-9]{64}(:.+)?$/.source, modes: ['SHA-256', 'RIPEMD-256', 'Haval-256', 'GOST R 34_11-94', 'GOST CryptoPro S-Box', 'SHA3-256', 'Skein-256', 'Skein-512(256)', 'Ventrilo', 'sha256($pass_$salt)', 'sha256($salt_$pass)', 'sha256(unicode($pass)_$salt)', 'sha256($salt_unicode($pass))', 'HMAC-SHA256 (key = $pass)', 'HMAC-SHA256 (key = $salt)']},
    {regex: /^[A-F0-9]{64}(:.+)?$/.source, modes: ['SHA-256', 'RIPEMD-256', 'Haval-256', 'GOST R 34_11-94', 'GOST CryptoPro S-Box', 'SHA3-256', 'Skein-256', 'Skein-512(256)', 'Ventrilo', 'sha256($pass_$salt)', 'sha256($salt_$pass)', 'sha256(unicode($pass)_$salt)', 'sha256($salt_unicode($pass))', 'HMAC-SHA256 (key = $pass)', 'HMAC-SHA256 (key = $salt)']},
    {regex: /^[a-f0-9]{32}:[a-zA-Z0-9]{32}$/.source, modes: ['Joomla < v2_5_18']},
    {regex: /^[A-F0-9]{32}:[a-zA-Z0-9]{32}$/.source, modes: ['Joomla < v2_5_18']},
    {regex: /^[a-f-0-9]{32}:[a-f-0-9]{32}$/.source, modes: ['SAM(LM_Hash:NT_Hash)']},
    {regex: /^[A-F-0-9]{32}:[A-F-0-9]{32}$/.source, modes: ['SAM(LM_Hash:NT_Hash)']},
    {regex: /^(\$chap\$0\*)?[a-f0-9]{32}[*:][a-f0-9]{32}(:[0-9]{2})?$/.source, modes: ['MD5(Chap)', 'iSCSI CHAP Authentication']},
    {regex: /^(\$chap\$0\*)?[A-F0-9]{32}[*:][A-F0-9]{32}(:[0-9]{2})?$/.source, modes: ['MD5(Chap)', 'iSCSI CHAP Authentication']},
    {regex: /^\$episerver\$\*0\*[a-zA-Z0-9\/=+]+\*[a-zA-Z0-9\/=+]{27,28}$/.source, modes: ['EPiServer 6_x < v4']},
    {regex: /^{ssha256}[0-9]{2}\$[a-zA-Z0-9$\/.]{60}$/.source, modes: ['AIX(ssha256)']},
    {regex: /^[a-f0-9]{80}$/.source, modes: ['RIPEMD-320']},
    {regex: /^[A-F0-9]{80}$/.source, modes: ['RIPEMD-320']},
    {regex: /^\$episerver\$\*1\*[a-zA-Z0-9\/=+]+\*[a-zA-Z0-9\/=+]{42,43}$/.source, modes: ['EPiServer 6_x >= v4']},
    {regex: /^0x0100[a-f0-9]{88}$/.source, modes: ['MSSQL(2000)']},
    {regex: /^0x0100[A-F0-9]{88}$/.source, modes: ['MSSQL(2000)']},
    {regex: /^[a-f0-9]{96}$/.source, modes: ['SHA-384', 'SHA3-384', 'Skein-512(384)', 'Skein-1024(384)']},
    {regex: /^[A-F0-9]{96}$/.source, modes: ['SHA-384', 'SHA3-384', 'Skein-512(384)', 'Skein-1024(384)']},
    {regex: /^{SSHA512}[a-zA-Z0-9\/+]{96}$/.source, modes: ['SSHA-512(Base64)', 'LDAP(SSHA-512)']},
    {regex: /^{ssha512}[0-9]{2}\$[a-zA-Z0-9\/.]{16,48}\$[a-zA-Z0-9\/.]{86}$/.source, modes: ['AIX(ssha512)']},
    {regex: /^[a-f0-9]{128}(:.+)?$/.source, modes: ['SHA-512', 'Whirlpool', 'Salsa10', 'Salsa20', 'SHA3-512', 'Skein-512', 'Skein-1024(512)', 'sha512($pass_$salt)', 'sha512($salt_$pass)', 'sha512(unicode($pass)_$salt)', 'sha512($salt_unicode($pass))', 'HMAC-SHA512 (key = $pass)', 'HMAC-SHA512 (key = $salt)']},
    {regex: /^[A-F0-9]{128}(:.+)?$/.source, modes: ['SHA-512', 'Whirlpool', 'Salsa10', 'Salsa20', 'SHA3-512', 'Skein-512', 'Skein-1024(512)', 'sha512($pass_$salt)', 'sha512($salt_$pass)', 'sha512(unicode($pass)_$salt)', 'sha512($salt_unicode($pass))', 'HMAC-SHA512 (key = $pass)', 'HMAC-SHA512 (key = $salt)']},
    {regex: /^[a-f0-9]{136}$/.source, modes: ['OSX v10_7']},
    {regex: /^[A-F0-9]{136}$/.source, modes: ['OSX v10_7']},
    {regex: /^0x0200[a-f0-9]{136}$/.source, modes: ['MSSQL(2012)', 'MSSQL(2014)']},
    {regex: /^0x0200[A-F0-9]{136}$/.source, modes: ['MSSQL(2012)', 'MSSQL(2014)']},
    {regex: /^\$ml\$[0-9]+\$[a-f0-9]{64}\$[a-f0-9]{128}$/.source, modes: ['OSX v10_8', 'OSX v10_9']},
    {regex: /^\$ml\$[0-9]+\$[A-F0-9]{64}\$[A-F0-9]{128}$/.source, modes: ['OSX v10_8', 'OSX v10_9']},
    {regex: /^[a-f0-9]{256}$/.source, modes: ['Skein-1024']},
    {regex: /^[A-F0-9]{256}$/.source, modes: ['Skein-1024']},
    {regex: /^grub\.pbkdf2\.sha512\.[0-9]+\.([a-f0-9]{128,2048}\.|[0-9]+\.)?[a-f0-9]{128}$/.source, modes: ['GRUB 2']},
    {regex: /^grub\.pbkdf2\.sha512\.[0-9]+\.([A-F0-9]{128,2048}\.|[0-9]+\.)?[A-F0-9]{128}$/.source, modes: ['GRUB 2']},
    {regex: /^sha1\$[a-zA-Z0-9]+\$[a-f0-9]{40}$/.source, modes: ['Django(SHA-1)']},
    {regex: /^sha1\$[a-zA-Z0-9]+\$[A-F0-9]{40}$/.source, modes: ['Django(SHA-1)']},
    {regex: /^[a-f0-9]{49}$/.source, modes: ['Citrix Netscaler']},
    {regex: /^[A-F0-9]{49}$/.source, modes: ['Citrix Netscaler']},
    {regex: /^\$S\$[a-zA-Z0-9\/.]{52}$/.source, modes: ['Drupal > v7_x']},
    {regex: /^\$5\$(rounds=[0-9]+\$)?[a-zA-Z0-9\/.]{0,16}\$[a-zA-Z0-9\/.]{43}$/.source, modes: ['SHA-256 Crypt']},
    {regex: /^0x[a-f0-9]{4}[a-f0-9]{16}[a-f0-9]{64}$/.source, modes: ['Sybase ASE']},
    {regex: /^0x[a-f0-9]{4}[A-F0-9]{16}[A-F0-9]{64}$/.source, modes: ['Sybase ASE']},
    {regex: /^\$6\$(rounds=[0-9]+\$)?[a-zA-Z0-9\/.]{0,16}\$[a-zA-Z0-9\/.]{86}$/.source, modes: ['SHA-512 Crypt']},
    {regex: /^\$sha\$[a-zA-Z0-9]{1,16}\$([a-f0-9]{32}|[a-f0-9]{40}|[a-f0-9]{64}|[a-f0-9]{128}|[a-f0-9]{140})$/.source, modes: ['Minecraft(AuthMe Reloaded)']},
    {regex: /^\$sha\$[a-zA-Z0-9]{1,16}\$([a-f0-9]{32}|[a-f0-9]{40}|[a-f0-9]{64}|[A-F0-9]{128}|[A-F0-9]{140})$/.source, modes: ['Minecraft(AuthMe Reloaded)']},
    {regex: /^sha256\$[a-zA-Z0-9]+\$[a-f0-9]{64}$/.source, modes: ['Django(SHA-256)']},
    {regex: /^sha256\$[a-zA-Z0-9]+\$[A-F0-9]{64}$/.source, modes: ['Django(SHA-256)']},
    {regex: /^sha384\$[a-zA-Z0-9]+\$[a-f0-9]{96}$/.source, modes: ['Django(SHA-384)']},
    {regex: /^sha384\$[a-zA-Z0-9]+\$[A-F0-9]{96}$/.source, modes: ['Django(SHA-384)']},
    {regex: /^crypt1:[a-zA-Z0-9+=]{12}:[a-zA-Z0-9+=]{12}$/.source, modes: ['Clavister Secure Gateway']},
    {regex: /^[a-f0-9]{112}$/.source, modes: ['Cisco VPN Client(PCF-File)']},
    {regex: /^[A-F0-9]{112}$/.source, modes: ['Cisco VPN Client(PCF-File)']},
    {regex: /^[a-f0-9]{1329}$/.source, modes: ['Microsoft MSTSC(RDP-File)']},
    {regex: /^[A-F0-9]{1329}$/.source, modes: ['Microsoft MSTSC(RDP-File)']},
    {regex: /^[^\\\/:*?"<>|]{1,20}[:]{2,3}([^\\\/:*?"<>|]{1,20})?:[a-f0-9]{48}:[a-f0-9]{48}:[a-f0-9]{16}$/.source, modes: ['NetNTLMv1-VANILLA / NetNTLMv1+ESS']},
    {regex: /^[^\\\/:*?"<>|]{1,20}[:]{2,3}([^\\\/:*?"<>|]{1,20})?:[a-f0-9]{48}:[A-F0-9]{48}:[A-F0-9]{16}$/.source, modes: ['NetNTLMv1-VANILLA / NetNTLMv1+ESS']},
    {regex: /^([^\\\/:*?"<>|]{1,20}\\)?[^\\\/:*?"<>|]{1,20}[:]{2,3}([^\\\/:*?"<>|]{1,20}:)?[^\\\/:*?"<>|]{1,20}:[a-f0-9]{32}:[a-f0-9]+$/.source, modes: ['NetNTLMv2']},
    {regex: /^([^\\\/:*?"<>|]{1,20}\\)?[^\\\/:*?"<>|]{1,20}[:]{2,3}([^\\\/:*?"<>|]{1,20}:)?[^\\\/:*?"<>|]{1,20}:[A-F0-9]{32}:[A-F0-9]+$/.source, modes: ['NetNTLMv2']},
    {regex: /^\$(krb5pa|mskrb5)\$([0-9]{2})?\$.+\$[a-f0-9]{1,}$/.source, modes: ['Kerberos 5 AS-REQ Pre-Auth']},
    {regex: /^\$(krb5pa|mskrb5)\$([0-9]{2})?\$.+\$[A-F0-9]{1,}$/.source, modes: ['Kerberos 5 AS-REQ Pre-Auth']},
    {regex: /^\$scram\$[0-9]+\$[a-zA-Z0-9\/.]{16}\$sha-1=[a-zA-Z0-9\/.]{27},sha-256=[a-zA-Z0-9\/.]{43},sha-512=[a-zA-Z0-9\/.]{86}$/.source, modes: ['SCRAM Hash']},
    {regex: /^[a-f0-9]{40}:[a-f0-9]{0,32}$/.source, modes: ['Redmine Project Management Web App']},
    {regex: /^[A-F0-9]{40}:[A-F0-9]{0,32}$/.source, modes: ['Redmine Project Management Web App']},
    {regex: /^(.+)?\$[a-f0-9]{16}$/.source, modes: ['SAP CODVN B (BCODE)']},
    {regex: /^(.+)?\$[A-F0-9]{16}$/.source, modes: ['SAP CODVN B (BCODE)']},
    {regex: /^(.+)?\$[a-f0-9]{40}$/.source, modes: ['SAP CODVN F/G (PASSCODE)']},
    {regex: /^(.+)?\$[A-F0-9]{40}$/.source, modes: ['SAP CODVN F/G (PASSCODE)']},
    {regex: /^0x[a-f0-9]{60}\s0x[a-f0-9]{40}$/.source, modes: ['EPi']},
    {regex: /^0x[A-F0-9]{60}\s0x[A-F0-9]{40}$/.source, modes: ['EPi']},
    {regex: /^[a-f0-9]{40}:[^*]{1,25}$/.source, modes: ['SMF >= v1_1']},
    {regex: /^[A-F0-9]{40}:[^*]{1,25}$/.source, modes: ['SMF >= v1_1']},
    {regex: /^(\$wbb3\$\*1\*)?[a-f0-9]{40}[:*][a-f0-9]{40}$/.source, modes: ['Woltlab Burning Board 3_x']},
    {regex: /^(\$wbb3\$\*1\*)?[A-F0-9]{40}[:*][A-F0-9]{40}$/.source, modes: ['Woltlab Burning Board 3_x']},
    {regex: /^[a-f0-9]{130}(:[a-f0-9]{40})?$/.source, modes: ['IPMI2 RAKP HMAC-SHA1']},
    {regex: /^[A-F0-9]{130}(:[A-F0-9]{40})?$/.source, modes: ['IPMI2 RAKP HMAC-SHA1']},
    {regex: /^[a-f0-9]{32}:[0-9]+:[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/.source, modes: ['Lastpass']},
    {regex: /^[A-F0-9]{32}:[0-9]+:[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/.source, modes: ['Lastpass']},
    {regex: /^[a-zA-Z0-9\/.]{16}([:$].{1,})?$/.source, modes: ['Cisco-ASA(MD5)']},
    {regex: /^\$vnc\$\*[a-f0-9]{32}\*[a-f0-9]{32}$/.source, modes: ['VNC']},
    {regex: /^\$vnc\$\*[A-F0-9]{32}\*[A-F0-9]{32}$/.source, modes: ['VNC']},
    {regex: /^[a-vA-V0-9]{32}(:([a-zA-Z0-9-]+\.)?[a-zA-Z0-9-.]+\.[a-z]{2,7}:.+:[0-9]+)?$/.source, modes: ['DNSSEC(NSEC3)']},
    {regex: /^[a-vA-V0-9]{32}(\.[a-zA-Z0-9-.]*)?$/.source, modes: ['DNSSEC(NSEC3)']}, // https://www.ietf.org/rfc/rfc5155.txt Base 32 Encoding with Extended Hex Alphabet for hash owner name
    {regex: /^(user-.+:)?\$racf\$\*.+\*[a-f0-9]{16}$/.source, modes: ['RACF']},
    {regex: /^(user-.+:)?\$racf\$\*.+\*[A-F0-9]{16}$/.source, modes: ['RACF']},
    {regex: /^\$3\$\$[a-f0-9]{32}$/.source, modes: ['NTHash(FreeBSD Variant)']},
    {regex: /^\$3\$\$[A-F0-9]{32}$/.source, modes: ['NTHash(FreeBSD Variant)']},
    {regex: /^\$sha1\$[0-9]+\$[a-zA-Z0-9\/.]{0,64}\$[a-zA-Z0-9\/.]{28}$/.source, modes: ['SHA-1 Crypt']},
    {regex: /^[a-f0-9]{70}$/.source, modes: ['hMailServer']},
    {regex: /^[A-F0-9]{70}$/.source, modes: ['hMailServer']},
    {regex: /^[:$][AB][:$]([a-f0-9]{1,8}[:$])?[a-f0-9]{32}$/.source, modes: ['MediaWiki']},
    {regex: /^[:$][AB][:$]([A-F0-9]{1,8}[:$])?[A-F0-9]{32}$/.source, modes: ['MediaWiki']},
    {regex: /^[a-f0-9]{140}$/.source, modes: ['Minecraft(xAuth)']},
    {regex: /^[A-F0-9]{140}$/.source, modes: ['Minecraft(xAuth)']},
    {regex: /^\$pbkdf2(-sha1)?\$[0-9]+\$[a-zA-Z0-9\/.]+\$[a-zA-Z0-9\/.]{27}$/.source, modes: ['PBKDF2-SHA1(Generic)']},
    {regex: /^\$pbkdf2-sha256\$[0-9]+\$[a-zA-Z0-9\/.]+\$[a-zA-Z0-9\/.]{43}$/.source, modes: ['PBKDF2-SHA256(Generic)']},
    {regex: /^\$pbkdf2-sha512\$[0-9]+\$[a-zA-Z0-9\/.]+\$[a-zA-Z0-9\/.]{86}$/.source, modes: ['PBKDF2-SHA512(Generic)']},
    {regex: /^\$p5k2\$[0-9]+\$[a-zA-Z0-9\/+=-]+\$[a-zA-Z0-9\/+-]{27}=$/.source, modes: ['PBKDF2(Cryptacular)']},
    {regex: /^\$p5k2\$[0-9]+\$[a-zA-Z0-9\/.]+\$[a-zA-Z0-9\/.]{32}$/.source, modes: ['PBKDF2(Dwayne Litzenberger)']},
    {regex: /^{FSHP[0123]\|[0-9]+\|[0-9]+}[a-zA-Z0-9\/+=]+$/.source, modes: ['Fairly Secure Hashed Password']},
    {regex: /^\$PHPS\$.+\$[a-f0-9]{32}$/.source, modes: ['PHPS']},
    {regex: /^\$PHPS\$.+\$[A-F0-9]{32}$/.source, modes: ['PHPS']},
    {regex: /^[0-9]{4}:[a-f0-9]{16}:[a-f0-9]{2080}$/.source, modes: ['1Password(Agile Keychain)']},
    {regex: /^[0-9]{4}:[A-F0-9]{16}:[A-F0-9]{2080}$/.source, modes: ['1Password(Agile Keychain)']},
    {regex: /^[a-f0-9]{64}:[a-f0-9]{32}:[0-9]{5}:[a-f0-9]{608}$/.source, modes: ['1Password(Cloud Keychain)']},
    {regex: /^[a-f0-9]{64}:[A-F0-9]{32}:[0-9]{5}:[A-F0-9]{608}$/.source, modes: ['1Password(Cloud Keychain)']},
    {regex: /^[a-f0-9]{256}:[a-f0-9]{256}:[a-f0-9]{16}:[a-f0-9]{16}:[a-f0-9]{320}:[a-f0-9]{16}:[a-f0-9]{40}:[a-f0-9]{40}:[a-f0-9]{32}$/.source, modes: ['IKE-PSK MD5']},
    {regex: /^[a-f0-9]{256}:[a-f0-9]{256}:[a-f0-9]{16}:[a-f0-9]{16}:[a-f0-9]{320}:[a-f0-9]{16}:[a-f0-9]{40}:[A-F0-9]{40}:[A-F0-9]{32}$/.source, modes: ['IKE-PSK MD5']},
    {regex: /^[a-f0-9]{256}:[a-f0-9]{256}:[a-f0-9]{16}:[a-f0-9]{16}:[a-f0-9]{320}:[a-f0-9]{16}:[a-f0-9]{40}:[a-f0-9]{40}:[a-f0-9]{40}$/.source, modes: ['IKE-PSK SHA1']},
    {regex: /^[a-f0-9]{256}:[a-f0-9]{256}:[a-f0-9]{16}:[a-f0-9]{16}:[a-f0-9]{320}:[a-f0-9]{16}:[a-f0-9]{40}:[A-F0-9]{40}:[A-F0-9]{40}$/.source, modes: ['IKE-PSK SHA1']},
    {regex: /^[a-zA-Z0-9\/+]{27}=$/.source, modes: ['PeopleSoft']},
    {regex: /^crypt\$[a-f0-9]{5}\$[a-zA-Z0-9\/.]{13}$/.source, modes: ['Django(DES Crypt Wrapper)']},
    {regex: /^crypt\$[A-F0-9]{5}\$[a-zA-Z0-9\/.]{13}$/.source, modes: ['Django(DES Crypt Wrapper)']},
    {regex: /^(\$django\$\*1\*)?pbkdf2_sha256\$[0-9]+\$[a-zA-Z0-9]+\$[a-zA-Z0-9\/+=]{44}$/.source, modes: ['Django(PBKDF2-HMAC-SHA256)']},
    {regex: /^pbkdf2_sha1\$[0-9]+\$[a-zA-Z0-9]+\$[a-zA-Z0-9\/+=]{28}$/.source, modes: ['Django(PBKDF2-HMAC-SHA1)']},
    {regex: /^bcrypt(\$2[axy]|\$2)\$[0-9]{2}\$[a-zA-Z0-9\/.]{53}$/.source, modes: ['Django(bcrypt)']},
    {regex: /^md5\$[a-f0-9]+\$[a-f0-9]{32}$/.source, modes: ['Django(MD5)']},
    {regex: /^md5\$[A-F0-9]+\$[A-F0-9]{32}$/.source, modes: ['Django(MD5)']},
    {regex: /^\{PKCS5S2}[a-zA-Z0-9\/+]{64}$/.source, modes: ['PBKDF2(Atlassian)']},
    {regex: /^md5[a-f0-9]{32}$/.source, modes: ['PostgreSQL MD5']},
    {regex: /^md5[A-F0-9]{32}$/.source, modes: ['PostgreSQL MD5']},
    {regex: /^\([a-zA-Z0-9\/+]{49}\)$/.source, modes: ['Lotus Notes/Domino 8']},
    {regex: /^SCRYPT:[0-9]{1,}:[0-9]{1}:[0-9]{1}:[a-zA-Z0-9:\/+=]{1,}$/.source, modes: ['scrypt']},
    {regex: /^\$8\$[a-zA-Z0-9\/.]{14}\$[a-zA-Z0-9\/.]{43}$/.source, modes: ['Cisco Type 8']},
    {regex: /^\$9\$[a-zA-Z0-9\/.]{14}\$[a-zA-Z0-9\/.]{43}$/.source, modes: ['Cisco Type 9']},
    {regex: /^\$office\$\*2007\*[0-9]{2}\*[0-9]{3}\*[0-9]{2}\*[a-zA-Z0-9]{32}\*[a-zA-Z0-9]{32}\*[a-zA-Z0-9]{40}$/.source, modes: ['Microsoft Office 2007']},
    {regex: /^\$office\$\*2010\*[0-9]{6}\*[0-9]{3}\*[0-9]{2}\*[a-zA-Z0-9]{32}\*[a-zA-Z0-9]{32}\*[a-zA-Z0-9]{64}$/.source, modes: ['Microsoft Office 2010']},
    {regex: /^\$office\$\*2013\*[0-9]{6}\*[0-9]{3}\*[0-9]{2}\*[a-zA-Z0-9]{32}\*[a-zA-Z0-9]{32}\*[a-zA-Z0-9]{64}$/.source, modes: ['Microsoft Office 2013']},
    {regex: /^\$fde\$[0-9]{2}\$[a-f0-9]{32}\$[0-9]{2}\$[a-f0-9]{32}\$[a-f0-9]{3072}$/.source, modes: ['Android FDE <= 4_3']},
    {regex: /^\$fde\$[0-9]{2}\$[a-f0-9]{32}\$[0-9]{2}\$[A-F0-9]{32}\$[A-F0-9]{3072}$/.source, modes: ['Android FDE <= 4_3']},
    {regex: /^\$oldoffice\$[01]\*[a-f0-9]{32}\*[a-f0-9]{32}\*[a-f0-9]{32}$/.source, modes: ['Microsoft Office <= 2003 (MD5+RC4)', 'Microsoft Office <= 2003 (MD5+RC4) collider-mode #1', 'Microsoft Office <= 2003 (MD5+RC4) collider-mode #2']},
    {regex: /^\$oldoffice\$[01]\*[a-f0-9]{32}\*[A-F0-9]{32}\*[A-F0-9]{32}$/.source, modes: ['Microsoft Office <= 2003 (MD5+RC4)', 'Microsoft Office <= 2003 (MD5+RC4) collider-mode #1', 'Microsoft Office <= 2003 (MD5+RC4) collider-mode #2']},
    {regex: /^\$oldoffice\$[34]\*[a-f0-9]{32}\*[a-f0-9]{32}\*[a-f0-9]{40}$/.source, modes: ['Microsoft Office <= 2003 (SHA1+RC4)', 'Microsoft Office <= 2003 (SHA1+RC4) collider-mode #1', 'Microsoft Office <= 2003 (SHA1+RC4) collider-mode #2']},
    {regex: /^\$oldoffice\$[34]\*[a-f0-9]{32}\*[A-F0-9]{32}\*[A-F0-9]{40}$/.source, modes: ['Microsoft Office <= 2003 (SHA1+RC4)', 'Microsoft Office <= 2003 (SHA1+RC4) collider-mode #1', 'Microsoft Office <= 2003 (SHA1+RC4) collider-mode #2']},
    {regex: /^(\$radmin2\$)?[a-f0-9]{32}$/.source, modes: ['RAdmin v2_x']},
    {regex: /^(\$radmin2\$)?[A-F0-9]{32}$/.source, modes: ['RAdmin v2_x']},
    {regex: /^{x-issha,\s[0-9]{4}}[a-zA-Z0-9\/+=]+$/.source, modes: ['SAP CODVN H (PWDSALTEDHASH) iSSHA-1']},
    {regex: /^\$cram_md5\$[a-zA-Z0-9\/+=-]+\$[a-zA-Z0-9\/+=-]{52}$/.source, modes: ['CRAM-MD5']},
    {regex: /^[a-f0-9]{16}:2:4:[a-f0-9]{32}$/.source, modes: ['SipHash']},
    {regex: /^[A-F0-9]{16}:2:4:[A-F0-9]{32}$/.source, modes: ['SipHash']},
    {regex: /^bcrypt_sha256\$\$(2[axy]|2)\$[0-9]+\$[a-zA-Z0-9\/.]{53}$/.source, modes: ['Django(bcrypt-SHA256)']},
    {regex: /^\$postgres\$.[^\*]+[*:][a-f0-9]{1,32}[*:][a-f0-9]{32}$/.source, modes: ['PostgreSQL Challenge-Response Authentication (MD5)']},
    {regex: /^\$postgres\$.[^\*]+[*:][A-F0-9]{1,32}[*:][A-F0-9]{32}$/.source, modes: ['PostgreSQL Challenge-Response Authentication (MD5)']},
    {regex: /^\$siemens-s7\$[0-9]{1}\$[a-f0-9]{40}\$[a-f0-9]{40}$/.source, modes: ['Siemens-S7']},
    {regex: /^\$siemens-s7\$[0-9]{1}\$[A-F0-9]{40}\$[A-F0-9]{40}$/.source, modes: ['Siemens-S7']},
    {regex: /^sha256[:$][0-9]+[:$][a-zA-Z0-9\/+]+[:$][a-zA-Z0-9\/+]{32,128}$/.source, modes: ['PBKDF2-HMAC-SHA256(PHP)']},
    {regex: /^\$mysqlna\$[a-f0-9]{40}[:*][a-f0-9]{40}$/.source, modes: ['MySQL Challenge-Response Authentication (SHA1)']},
    {regex: /^\$mysqlna\$[A-F0-9]{40}[:*][A-F0-9]{40}$/.source, modes: ['MySQL Challenge-Response Authentication (SHA1)']},
    {regex: /^\$pdf\$[24]\*[34]\*128\*[0-9-]{1,5}\*1\*(16|32)\*[a-f0-9]{32,64}\*32\*[a-f0-9]{64}\*(8|16|32)\*[a-f0-9]{16,64}$/.source, modes: ['PDF 1.4 - 1.6 (Acrobat 5 - 8)']},
    {regex: /^\$pdf\$[24]\*[34]\*128\*[0-9-]{1,5}\*1\*(16|32)\*[a-f0-9]{32,64}\*32\*[A-F0-9]{64}\*(8|16|32)\*[A-F0-9]{16,64}$/.source, modes: ['PDF 1.4 - 1.6 (Acrobat 5 - 8)']},
    // https://en.bitcoin.it/wiki/Invoice_address
    // https://en.bitcoin.it/wiki/Base58Check_encoding (the characters 0, O, I, and l are excluded)
    {regex: /^1[a-km-zA-HJ-NP-Z1-9]{25,35}$/.source, modes: ['Bitcoin P2PKH Base58Check']},
    {regex: /^3[a-km-zA-HJ-NP-Z1-9]{33}$/.source, modes: ['Bitcoin P2SH Base58Check']},
    // Bech32 https://en.bitcoin.it/wiki/BIP_0173 //Too permissive
    // {regex: /^[\!\"\#\*\%\&\'\(\)\*\+\,\-\.\/\:\;\<\=\>\?\@\[\\\]\^\_\`\{\|\}\~a-zA-Z0-9]{1,83}1[02-9ac-hj-np-z]{6,88}$/.source, modes: ['Bech32']},
    {regex: /^bc1q[02-9ac-hj-np-z]{38}$/.source, modes: ['Bitcoin P2WPKH SegWit Bech32']},
    {regex: /^BC1Q[02-9AC-HJ-NP-Z]{38}$/.source, modes: ['Bitcoin P2WPKH SegWit Bech32']},
    {regex: /^tb1[02-9ac-hj-np-z]{38}$/.source, modes: ['Bitcoin Test address']},
    {regex: /^bc1p[02-9ac-hj-np-z]{58}$/.source, modes: ['Bitcoin P2TR SegWit Bech32']},
    {regex: /^BC1P[02-9AC-HJ-NP-Z]{58}$/.source, modes: ['Bitcoin P2TR SegWit Bech32']}
];

// ===== INIT =====

var HashIdentifierInspector:InspectorFactory = new InspectorFactory({
    startStep: INSPECTOR_TYPE.POST_DEV_SCAN,
    version: "1.0.31",
    tags: hashIdentifierTags,
    hookSet: {
        id: "HashIdentifier",
        name: "Hash Identifier",
        description: "Identify some hash function from a hash value",
        strategies:[]
    },
    color: JSON.stringify(regexToHash),
    eventListenerSources: {
        "string.instance.new": {
            lang: "ts",
            source: `
                //<ts>={
                let ctx: Record<string,any> = pEvent.getContext();
                const INSPECTOR_HASHID_ID: string = "HashIdentifier";
                let matchedHashes = new Set<string>();
                if ((pEvent.getData() != null) && (pEvent.getData().value != null)) {
                    const HASH_TAG_CATEGORY_NAME = "crypto.hash";
                    let strToTest = pEvent.getData().value;
                    var regexToHash = JSON.parse(ctx.getInspectors()[INSPECTOR_HASHID_ID].factory.color);
                    regexToHash.forEach( (regex_hash_dict) => {
                        if (new RegExp(regex_hash_dict['regex']).test(strToTest)) {
                            regex_hash_dict['modes'].forEach( (hash) => {
                                var hashTagId = HASH_TAG_CATEGORY_NAME + '.' + hash.toString();
                                matchedHashes.add(hashTagId);
                            }
                        }
                    }
                    if (matchedHashes.size >= 1) {
                        console.log("[INSPECTOR][HASHIDENTIFIER] Hash pattern detected in:", strToTest);
                        console.log("List of possible hashes:", matchedHashes.toString());
                        matchedHashes.forEach( (hashTagId) => {
                            pEvent.getData().addTag(ctx.getTagManager().getTag(hashTagId));
                        }
                    }
                }
            `
        }
    }
});

export default HashIdentifierInspector;
