import {Endianness} from "../core/Endianness.js";
import InputEventCode from "./InputEventCode.js";
import EncodedToken from "../platform/EncodedToken.js";

//Source: https://docs.kernel.org/input/event-codes.html



const AndroidSynEventCodes = [
    InputEventCode.SYN_REPORT,
    InputEventCode.SYN_CONFIG,
    InputEventCode.SYN_MT_REPORT,
    InputEventCode.SYN_DROPPED,
]

const AndroidKeyEventCodes = [
    InputEventCode.KEY_RESERVED,
    InputEventCode.KEY_ESC,
    InputEventCode.KEY_1,
    InputEventCode.KEY_2,
    InputEventCode.KEY_3,
    InputEventCode.KEY_4,
    InputEventCode.KEY_5,
    InputEventCode.KEY_6,
    InputEventCode.KEY_7,
    InputEventCode.KEY_8,
    InputEventCode.KEY_9,
    InputEventCode.KEY_0,
    InputEventCode.KEY_MINUS,
    InputEventCode.KEY_EQUAL,
    InputEventCode.KEY_BACKSPACE,
    InputEventCode.KEY_TAB,
    InputEventCode.KEY_Q,
    InputEventCode.KEY_W,
    InputEventCode.KEY_E,
    InputEventCode.KEY_R,
    InputEventCode.KEY_T,
    InputEventCode.KEY_Y,
    InputEventCode.KEY_U,
    InputEventCode.KEY_I,
    InputEventCode.KEY_O,
    InputEventCode.KEY_P,
    InputEventCode.KEY_LEFTBRACE,
    InputEventCode.KEY_RIGHTBRACE,
    InputEventCode.KEY_ENTER,
    InputEventCode.KEY_LEFTCTRL,
    InputEventCode.KEY_A,
    InputEventCode.KEY_S,
    InputEventCode.KEY_D,
    InputEventCode.KEY_F,
    InputEventCode.KEY_G,
    InputEventCode.KEY_H,
    InputEventCode.KEY_J,
    InputEventCode.KEY_K,
    InputEventCode.KEY_L,
    InputEventCode.KEY_SEMICOLON,
    InputEventCode.KEY_APOSTROPHE,
    InputEventCode.KEY_GRAVE,
    InputEventCode.KEY_LEFTSHIFT,
    InputEventCode.KEY_BACKSLASH,
    InputEventCode.KEY_Z,
    InputEventCode.KEY_X,
    InputEventCode.KEY_C,
    InputEventCode.KEY_V,
    InputEventCode.KEY_B,
    InputEventCode.KEY_N,
    InputEventCode.KEY_M,
    InputEventCode.KEY_COMMA,
    InputEventCode.KEY_DOT,
    InputEventCode.KEY_SLASH,
    InputEventCode.KEY_RIGHTSHIFT,
    InputEventCode.KEY_KPASTERISK,
    InputEventCode.KEY_LEFTALT,
    InputEventCode.KEY_SPACE,
    InputEventCode.KEY_CAPSLOCK,
    InputEventCode.KEY_F1,
    InputEventCode.KEY_F2,
    InputEventCode.KEY_F3,
    InputEventCode.KEY_F4,
    InputEventCode.KEY_F5,
    InputEventCode.KEY_F6,
    InputEventCode.KEY_F7,
    InputEventCode.KEY_F8,
    InputEventCode.KEY_F9,
    InputEventCode.KEY_F10,
    InputEventCode.KEY_NUMLOCK,
    InputEventCode.KEY_SCROLLLOCK,
    InputEventCode.KEY_KP7,
    InputEventCode.KEY_KP8,
    InputEventCode.KEY_KP9,
    InputEventCode.KEY_KPMINUS,
    InputEventCode.KEY_KP4,
    InputEventCode.KEY_KP5,
    InputEventCode.KEY_KP6,
    InputEventCode.KEY_KPPLUS,
    InputEventCode.KEY_KP1,
    InputEventCode.KEY_KP2,
    InputEventCode.KEY_KP3,
    InputEventCode.KEY_KP0,
    InputEventCode.KEY_KPDOT,
    InputEventCode.KEY_ZENKAKUHANKAKU,
    InputEventCode.KEY_102ND,
    InputEventCode.KEY_F11,
    InputEventCode.KEY_F12,
    InputEventCode.KEY_RO,
    InputEventCode.KEY_KATAKANA,
    InputEventCode.KEY_HIRAGANA,
    InputEventCode.KEY_HENKAN,
    InputEventCode.KEY_KATAKANAHIRAGANA,
    InputEventCode.KEY_MUHENKAN,
    InputEventCode.KEY_KPJPCOMMA,
    InputEventCode.KEY_KPENTER,
    InputEventCode.KEY_RIGHTCTRL,
    InputEventCode.KEY_KPSLASH,
    InputEventCode.KEY_SYSRQ,
    InputEventCode.KEY_RIGHTALT,
    InputEventCode.KEY_LINEFEED,
    InputEventCode.KEY_HOME,
    InputEventCode.KEY_UP,
    InputEventCode.KEY_PAGEUP,
    InputEventCode.KEY_LEFT,
    InputEventCode.KEY_RIGHT,
    InputEventCode.KEY_END,
    InputEventCode.KEY_DOWN,
    InputEventCode.KEY_PAGEDOWN,
    InputEventCode.KEY_INSERT,
    InputEventCode.KEY_DELETE,
    InputEventCode.KEY_MACRO,
    InputEventCode.KEY_MUTE,
    InputEventCode.KEY_VOLUMEDOWN,
    InputEventCode.KEY_VOLUMEUP,
    InputEventCode.KEY_POWER,
    InputEventCode.KEY_KPEQUAL,
    InputEventCode.KEY_KPPLUSMINUS,
    InputEventCode.KEY_PAUSE,
    InputEventCode.KEY_SCALE,
    InputEventCode.KEY_KPCOMMA,
    InputEventCode.KEY_HANGEUL,
    InputEventCode.KEY_HANGUEL,
    InputEventCode.KEY_HANJA,
    InputEventCode.KEY_YEN,
    InputEventCode.KEY_LEFTMETA,
    InputEventCode.KEY_RIGHTMETA,
    InputEventCode.KEY_COMPOSE,
    InputEventCode.KEY_STOP,
    InputEventCode.KEY_AGAIN,
    InputEventCode.KEY_PROPS,
    InputEventCode.KEY_UNDO,
    InputEventCode.KEY_FRONT,
    InputEventCode.KEY_COPY,
    InputEventCode.KEY_OPEN,
    InputEventCode.KEY_PASTE,
    InputEventCode.KEY_FIND,
    InputEventCode.KEY_CUT,
    InputEventCode.KEY_HELP,
    InputEventCode.KEY_MENU,
    InputEventCode.KEY_CALC,
    InputEventCode.KEY_SETUP,
    InputEventCode.KEY_SLEEP,
    InputEventCode.KEY_WAKEUP,
    InputEventCode.KEY_FILE,
    InputEventCode.KEY_SENDFILE,
    InputEventCode.KEY_DELETEFILE,
    InputEventCode.KEY_XFER,
    InputEventCode.KEY_PROG1,
    InputEventCode.KEY_PROG2,
    InputEventCode.KEY_WWW,
    InputEventCode.KEY_MSDOS,
    InputEventCode.KEY_COFFEE,
    InputEventCode.KEY_SCREENLOCK,
    InputEventCode.KEY_ROTATE_DISPLAY,
    InputEventCode.KEY_DIRECTION,
    InputEventCode.KEY_CYCLEWINDOWS,
    InputEventCode.KEY_MAIL,
    InputEventCode.KEY_BOOKMARKS,
    InputEventCode.KEY_COMPUTER,
    InputEventCode.KEY_BACK,
    InputEventCode.KEY_FORWARD,
    InputEventCode.KEY_CLOSECD,
    InputEventCode.KEY_EJECTCD,
    InputEventCode.KEY_EJECTCLOSECD,
    InputEventCode.KEY_NEXTSONG,
    InputEventCode.KEY_PLAYPAUSE,
    InputEventCode.KEY_PREVIOUSSONG,
    InputEventCode.KEY_STOPCD,
    InputEventCode.KEY_RECORD,
    InputEventCode.KEY_REWIND,
    InputEventCode.KEY_PHONE,
    InputEventCode.KEY_ISO,
    InputEventCode.KEY_CONFIG,
    InputEventCode.KEY_HOMEPAGE,
    InputEventCode.KEY_REFRESH,
    InputEventCode.KEY_EXIT,
    InputEventCode.KEY_MOVE,
    InputEventCode.KEY_EDIT,
    InputEventCode.KEY_SCROLLUP,
    InputEventCode.KEY_SCROLLDOWN,
    InputEventCode.KEY_KPLEFTPAREN,
    InputEventCode.KEY_KPRIGHTPAREN,
    InputEventCode.KEY_NEW,
    InputEventCode.KEY_REDO,
    InputEventCode.KEY_F13,
    InputEventCode.KEY_F14,
    InputEventCode.KEY_F15,
    InputEventCode.KEY_F16,
    InputEventCode.KEY_F17,
    InputEventCode.KEY_F18,
    InputEventCode.KEY_F19,
    InputEventCode.KEY_F20,
    InputEventCode.KEY_F21,
    InputEventCode.KEY_F22,
    InputEventCode.KEY_F23,
    InputEventCode.KEY_F24,
    InputEventCode.KEY_PLAYCD,
    InputEventCode.KEY_PAUSECD,
    InputEventCode.KEY_PROG3,
    InputEventCode.KEY_PROG4,
    InputEventCode.KEY_ALL_APPLICATIONS,
    InputEventCode.KEY_DASHBOARD,
    InputEventCode.KEY_SUSPEND,
    InputEventCode.KEY_CLOSE,
    InputEventCode.KEY_PLAY,
    InputEventCode.KEY_FASTFORWARD,
    InputEventCode.KEY_BASSBOOST,
    InputEventCode.KEY_PRINT,
    InputEventCode.KEY_HP,
    InputEventCode.KEY_CAMERA,
    InputEventCode.KEY_SOUND,
    InputEventCode.KEY_QUESTION,
    InputEventCode.KEY_EMAIL,
    InputEventCode.KEY_CHAT,
    InputEventCode.KEY_SEARCH,
    InputEventCode.KEY_CONNECT,
    InputEventCode.KEY_FINANCE,
    InputEventCode.KEY_SPORT,
    InputEventCode.KEY_SHOP,
    InputEventCode.KEY_ALTERASE,
    InputEventCode.KEY_CANCEL,
    InputEventCode.KEY_BRIGHTNESSDOWN,
    InputEventCode.KEY_BRIGHTNESSUP,
    InputEventCode.KEY_MEDIA,
    InputEventCode.KEY_SWITCHVIDEOMODE,
    InputEventCode.KEY_KBDILLUMTOGGLE,
    InputEventCode.KEY_KBDILLUMDOWN,
    InputEventCode.KEY_KBDILLUMUP,
    InputEventCode.KEY_SEND,
    InputEventCode.KEY_REPLY,
    InputEventCode.KEY_FORWARDMAIL,
    InputEventCode.KEY_SAVE,
    InputEventCode.KEY_DOCUMENTS,
    InputEventCode.KEY_BATTERY,
    InputEventCode.KEY_BLUETOOTH,
    InputEventCode.KEY_WLAN,
    InputEventCode.KEY_UWB,
    InputEventCode.KEY_UNKNOWN,
    InputEventCode.KEY_VIDEO_NEXT,
    InputEventCode.KEY_VIDEO_PREV,
    InputEventCode.KEY_BRIGHTNESS_CYCLE,
    InputEventCode.KEY_BRIGHTNESS_AUTO,
    InputEventCode.KEY_BRIGHTNESS_ZERO,
    InputEventCode.KEY_DISPLAY_OFF,
    InputEventCode.KEY_WWAN,
    InputEventCode.KEY_WIMAX,
    InputEventCode.KEY_RFKILL,
    InputEventCode.KEY_MICMUTE,
    InputEventCode.BTN_MISC,
    InputEventCode.BTN_0,
    InputEventCode.BTN_1,
    InputEventCode.BTN_2,
    InputEventCode.BTN_3,
    InputEventCode.BTN_4,
    InputEventCode.BTN_5,
    InputEventCode.BTN_6,
    InputEventCode.BTN_7,
    InputEventCode.BTN_8,
    InputEventCode.BTN_9,
    InputEventCode.BTN_MOUSE,
    InputEventCode.BTN_LEFT,
    InputEventCode.BTN_RIGHT,
    InputEventCode.BTN_MIDDLE,
    InputEventCode.BTN_SIDE,
    InputEventCode.BTN_EXTRA,
    InputEventCode.BTN_FORWARD,
    InputEventCode.BTN_BACK,
    InputEventCode.BTN_TASK,
    InputEventCode.BTN_JOYSTICK,
    InputEventCode.BTN_TRIGGER,
    InputEventCode.BTN_THUMB,
    InputEventCode.BTN_THUMB2,
    InputEventCode.BTN_TOP,
    InputEventCode.BTN_TOP2,
    InputEventCode.BTN_PINKIE,
    InputEventCode.BTN_BASE,
    InputEventCode.BTN_BASE2,
    InputEventCode.BTN_BASE3,
    InputEventCode.BTN_BASE4,
    InputEventCode.BTN_BASE5,
    InputEventCode.BTN_BASE6,
    InputEventCode.BTN_DEAD,
    InputEventCode.BTN_GAMEPAD,
    InputEventCode.BTN_SOUTH,
    InputEventCode.BTN_A,
    InputEventCode.BTN_EAST,
    InputEventCode.BTN_B,
    InputEventCode.BTN_C,
    InputEventCode.BTN_NORTH,
    InputEventCode.BTN_X,
    InputEventCode.BTN_WEST,
    InputEventCode.BTN_Y,
    InputEventCode.BTN_Z,
    InputEventCode.BTN_TL,
    InputEventCode.BTN_TR,
    InputEventCode.BTN_TL2,
    InputEventCode.BTN_TR2,
    InputEventCode.BTN_SELECT,
    InputEventCode.BTN_START,
    InputEventCode.BTN_MODE,
    InputEventCode.BTN_THUMBL,
    InputEventCode.BTN_THUMBR,
    InputEventCode.BTN_DIGI,
    InputEventCode.BTN_TOOL_PEN,
    InputEventCode.BTN_TOOL_RUBBER,
    InputEventCode.BTN_TOOL_BRUSH,
    InputEventCode.BTN_TOOL_PENCIL,
    InputEventCode.BTN_TOOL_AIRBRUSH,
    InputEventCode.BTN_TOOL_FINGER,
    InputEventCode.BTN_TOOL_MOUSE,
    InputEventCode.BTN_TOOL_LENS,
    InputEventCode.BTN_TOOL_QUINTTAP,
    InputEventCode.BTN_STYLUS3,
    InputEventCode.BTN_TOUCH,
    InputEventCode.BTN_STYLUS,
    InputEventCode.BTN_STYLUS2,
    InputEventCode.BTN_TOOL_DOUBLETAP,
    InputEventCode.BTN_TOOL_TRIPLETAP,
    InputEventCode.BTN_TOOL_QUADTAP,
    InputEventCode.BTN_WHEEL,
    InputEventCode.BTN_GEAR_DOWN,
    InputEventCode.BTN_GEAR_UP,
    InputEventCode.KEY_OK,
    InputEventCode.KEY_SELECT,
    InputEventCode.KEY_GOTO,
    InputEventCode.KEY_CLEAR,
    InputEventCode.KEY_POWER2,
    InputEventCode.KEY_OPTION,
    InputEventCode.KEY_INFO,
    InputEventCode.KEY_TIME,
    InputEventCode.KEY_VENDOR,
    InputEventCode.KEY_ARCHIVE,
    InputEventCode.KEY_PROGRAM,
    InputEventCode.KEY_CHANNEL,
    InputEventCode.KEY_FAVORITES,
    InputEventCode.KEY_EPG,
    InputEventCode.KEY_PVR,
    InputEventCode.KEY_MHP,
    InputEventCode.KEY_LANGUAGE,
    InputEventCode.KEY_TITLE,
    InputEventCode.KEY_SUBTITLE,
    InputEventCode.KEY_ANGLE,
    InputEventCode.KEY_FULL_SCREEN,
    InputEventCode.KEY_ZOOM,
    InputEventCode.KEY_MODE,
    InputEventCode.KEY_KEYBOARD,
    InputEventCode.KEY_ASPECT_RATIO,
    InputEventCode.KEY_SCREEN,
    InputEventCode.KEY_PC,
    InputEventCode.KEY_TV,
    InputEventCode.KEY_TV2,
    InputEventCode.KEY_VCR,
    InputEventCode.KEY_VCR2,
    InputEventCode.KEY_SAT,
    InputEventCode.KEY_SAT2,
    InputEventCode.KEY_CD,
    InputEventCode.KEY_TAPE,
    InputEventCode.KEY_RADIO,
    InputEventCode.KEY_TUNER,
    InputEventCode.KEY_PLAYER,
    InputEventCode.KEY_TEXT,
    InputEventCode.KEY_DVD,
    InputEventCode.KEY_AUX,
    InputEventCode.KEY_MP3,
    InputEventCode.KEY_AUDIO,
    InputEventCode.KEY_VIDEO,
    InputEventCode.KEY_DIRECTORY,
    InputEventCode.KEY_LIST,
    InputEventCode.KEY_MEMO,
    InputEventCode.KEY_CALENDAR,
    InputEventCode.KEY_RED,
    InputEventCode.KEY_GREEN,
    InputEventCode.KEY_YELLOW,
    InputEventCode.KEY_BLUE,
    InputEventCode.KEY_CHANNELUP,
    InputEventCode.KEY_CHANNELDOWN,
    InputEventCode.KEY_FIRST,
    InputEventCode.KEY_LAST,
    InputEventCode.KEY_AB,
    InputEventCode.KEY_NEXT,
    InputEventCode.KEY_RESTART,
    InputEventCode.KEY_SLOW,
    InputEventCode.KEY_SHUFFLE,
    InputEventCode.KEY_BREAK,
    InputEventCode.KEY_PREVIOUS,
    InputEventCode.KEY_DIGITS,
    InputEventCode.KEY_TEEN,
    InputEventCode.KEY_TWEN,
    InputEventCode.KEY_VIDEOPHONE,
    InputEventCode.KEY_GAMES,
    InputEventCode.KEY_ZOOMIN,
    InputEventCode.KEY_ZOOMOUT,
    InputEventCode.KEY_ZOOMRESET,
    InputEventCode.KEY_WORDPROCESSOR,
    InputEventCode.KEY_EDITOR,
    InputEventCode.KEY_SPREADSHEET,
    InputEventCode.KEY_GRAPHICSEDITOR,
    InputEventCode.KEY_PRESENTATION,
    InputEventCode.KEY_DATABASE,
    InputEventCode.KEY_NEWS,
    InputEventCode.KEY_VOICEMAIL,
    InputEventCode.KEY_ADDRESSBOOK,
    InputEventCode.KEY_MESSENGER,
    InputEventCode.KEY_DISPLAYTOGGLE,
    InputEventCode.KEY_BRIGHTNESS_TOGGLE,
    InputEventCode.KEY_SPELLCHECK,
    InputEventCode.KEY_LOGOFF,
    InputEventCode.KEY_DOLLAR,
    InputEventCode.KEY_EURO,
    InputEventCode.KEY_FRAMEBACK,
    InputEventCode.KEY_FRAMEFORWARD,
    InputEventCode.KEY_CONTEXT_MENU,
    InputEventCode.KEY_MEDIA_REPEAT,
    InputEventCode.KEY_10CHANNELSUP,
    InputEventCode.KEY_10CHANNELSDOWN,
    InputEventCode.KEY_IMAGES,
    InputEventCode.KEY_NOTIFICATION_CENTER,
    InputEventCode.KEY_PICKUP_PHONE,
    InputEventCode.KEY_HANGUP_PHONE,
    InputEventCode.KEY_DEL_EOL,
    InputEventCode.KEY_DEL_EOS,
    InputEventCode.KEY_INS_LINE,
    InputEventCode.KEY_DEL_LINE,
    InputEventCode.KEY_FN,
    InputEventCode.KEY_FN_ESC,
    InputEventCode.KEY_FN_F1,
    InputEventCode.KEY_FN_F2,
    InputEventCode.KEY_FN_F3,
    InputEventCode.KEY_FN_F4,
    InputEventCode.KEY_FN_F5,
    InputEventCode.KEY_FN_F6,
    InputEventCode.KEY_FN_F7,
    InputEventCode.KEY_FN_F8,
    InputEventCode.KEY_FN_F9,
    InputEventCode.KEY_FN_F10,
    InputEventCode.KEY_FN_F11,
    InputEventCode.KEY_FN_F12,
    InputEventCode.KEY_FN_1,
    InputEventCode.KEY_FN_2,
    InputEventCode.KEY_FN_D,
    InputEventCode.KEY_FN_E,
    InputEventCode.KEY_FN_F,
    InputEventCode.KEY_FN_S,
    InputEventCode.KEY_FN_B,
    InputEventCode.KEY_FN_RIGHT_SHIFT,
    InputEventCode.KEY_BRL_DOT1,
    InputEventCode.KEY_BRL_DOT2,
    InputEventCode.KEY_BRL_DOT3,
    InputEventCode.KEY_BRL_DOT4,
    InputEventCode.KEY_BRL_DOT5,
    InputEventCode.KEY_BRL_DOT6,
    InputEventCode.KEY_BRL_DOT7,
    InputEventCode.KEY_BRL_DOT8,
    InputEventCode.KEY_BRL_DOT9,
    InputEventCode.KEY_BRL_DOT10,
    InputEventCode.KEY_NUMERIC_0,
    InputEventCode.KEY_NUMERIC_1,
    InputEventCode.KEY_NUMERIC_2,
    InputEventCode.KEY_NUMERIC_3,
    InputEventCode.KEY_NUMERIC_4,
    InputEventCode.KEY_NUMERIC_5,
    InputEventCode.KEY_NUMERIC_6,
    InputEventCode.KEY_NUMERIC_7,
    InputEventCode.KEY_NUMERIC_8,
    InputEventCode.KEY_NUMERIC_9,
    InputEventCode.KEY_NUMERIC_STAR,
    InputEventCode.KEY_NUMERIC_POUND,
    InputEventCode.KEY_NUMERIC_A,
    InputEventCode.KEY_NUMERIC_B,
    InputEventCode.KEY_NUMERIC_C,
    InputEventCode.KEY_NUMERIC_D,
    InputEventCode.KEY_CAMERA_FOCUS,
    InputEventCode.KEY_WPS_BUTTON,
    InputEventCode.KEY_TOUCHPAD_TOGGLE,
    InputEventCode.KEY_TOUCHPAD_ON,
    InputEventCode.KEY_TOUCHPAD_OFF,
    InputEventCode.KEY_CAMERA_ZOOMIN,
    InputEventCode.KEY_CAMERA_ZOOMOUT,
    InputEventCode.KEY_CAMERA_UP,
    InputEventCode.KEY_CAMERA_DOWN,
    InputEventCode.KEY_CAMERA_LEFT,
    InputEventCode.KEY_CAMERA_RIGHT,
    InputEventCode.KEY_ATTENDANT_ON,
    InputEventCode.KEY_ATTENDANT_OFF,
    InputEventCode.KEY_ATTENDANT_TOGGLE,
    InputEventCode.KEY_LIGHTS_TOGGLE,
    InputEventCode.BTN_DPAD_UP,
    InputEventCode.BTN_DPAD_DOWN,
    InputEventCode.BTN_DPAD_LEFT,
    InputEventCode.BTN_DPAD_RIGHT,
    InputEventCode.KEY_ALS_TOGGLE,
    InputEventCode.KEY_ROTATE_LOCK_TOGGLE,
    InputEventCode.KEY_REFRESH_RATE_TOGGLE,
    InputEventCode.KEY_BUTTONCONFIG,
    InputEventCode.KEY_TASKMANAGER,
    InputEventCode.KEY_JOURNAL,
    InputEventCode.KEY_CONTROLPANEL,
    InputEventCode.KEY_APPSELECT,
    InputEventCode.KEY_SCREENSAVER,
    InputEventCode.KEY_VOICECOMMAND,
    InputEventCode.KEY_ASSISTANT,
    InputEventCode.KEY_KBD_LAYOUT_NEXT,
    InputEventCode.KEY_EMOJI_PICKER,
    InputEventCode.KEY_DICTATE,
    InputEventCode.KEY_CAMERA_ACCESS_ENABLE,
    InputEventCode.KEY_CAMERA_ACCESS_DISABLE,
    InputEventCode.KEY_CAMERA_ACCESS_TOGGLE,
    InputEventCode.KEY_ACCESSIBILITY,
    InputEventCode.KEY_DO_NOT_DISTURB,
    InputEventCode.KEY_BRIGHTNESS_MIN,
    InputEventCode.KEY_BRIGHTNESS_MAX,
    InputEventCode.KEY_KBDINPUTASSIST_PREV,
    InputEventCode.KEY_KBDINPUTASSIST_NEXT,
    InputEventCode.KEY_KBDINPUTASSIST_PREVGROUP,
    InputEventCode.KEY_KBDINPUTASSIST_NEXTGROUP,
    InputEventCode.KEY_KBDINPUTASSIST_ACCEPT,
    InputEventCode.KEY_KBDINPUTASSIST_CANCEL,
    InputEventCode.KEY_RIGHT_UP,
    InputEventCode.KEY_RIGHT_DOWN,
    InputEventCode.KEY_LEFT_UP,
    InputEventCode.KEY_LEFT_DOWN,
    InputEventCode.KEY_ROOT_MENU,
    InputEventCode.KEY_MEDIA_TOP_MENU,
    InputEventCode.KEY_NUMERIC_11,
    InputEventCode.KEY_NUMERIC_12,
    InputEventCode.KEY_AUDIO_DESC,
    InputEventCode.KEY_3D_MODE,
    InputEventCode.KEY_NEXT_FAVORITE,
    InputEventCode.KEY_STOP_RECORD,
    InputEventCode.KEY_PAUSE_RECORD,
    InputEventCode.KEY_VOD,
    InputEventCode.KEY_UNMUTE,
    InputEventCode.KEY_FASTREVERSE,
    InputEventCode.KEY_SLOWREVERSE,
    InputEventCode.KEY_DATA,
    InputEventCode.KEY_ONSCREEN_KEYBOARD,
    InputEventCode.KEY_PRIVACY_SCREEN_TOGGLE,
    InputEventCode.KEY_SELECTIVE_SCREENSHOT,
    InputEventCode.KEY_NEXT_ELEMENT,
    InputEventCode.KEY_PREVIOUS_ELEMENT,
    InputEventCode.KEY_AUTOPILOT_ENGAGE_TOGGLE,
    InputEventCode.KEY_MARK_WAYPOINT,
    InputEventCode.KEY_SOS,
    InputEventCode.KEY_NAV_CHART,
    InputEventCode.KEY_FISHING_CHART,
    InputEventCode.KEY_SINGLE_RANGE_RADAR,
    InputEventCode.KEY_DUAL_RANGE_RADAR,
    InputEventCode.KEY_RADAR_OVERLAY,
    InputEventCode.KEY_TRADITIONAL_SONAR,
    InputEventCode.KEY_CLEARVU_SONAR,
    InputEventCode.KEY_SIDEVU_SONAR,
    InputEventCode.KEY_NAV_INFO,
    InputEventCode.KEY_BRIGHTNESS_MENU,
    InputEventCode.KEY_MACRO1,
    InputEventCode.KEY_MACRO2,
    InputEventCode.KEY_MACRO3,
    InputEventCode.KEY_MACRO4,
    InputEventCode.KEY_MACRO5,
    InputEventCode.KEY_MACRO6,
    InputEventCode.KEY_MACRO7,
    InputEventCode.KEY_MACRO8,
    InputEventCode.KEY_MACRO9,
    InputEventCode.KEY_MACRO10,
    InputEventCode.KEY_MACRO11,
    InputEventCode.KEY_MACRO12,
    InputEventCode.KEY_MACRO13,
    InputEventCode.KEY_MACRO14,
    InputEventCode.KEY_MACRO15,
    InputEventCode.KEY_MACRO16,
    InputEventCode.KEY_MACRO17,
    InputEventCode.KEY_MACRO18,
    InputEventCode.KEY_MACRO19,
    InputEventCode.KEY_MACRO20,
    InputEventCode.KEY_MACRO21,
    InputEventCode.KEY_MACRO22,
    InputEventCode.KEY_MACRO23,
    InputEventCode.KEY_MACRO24,
    InputEventCode.KEY_MACRO25,
    InputEventCode.KEY_MACRO26,
    InputEventCode.KEY_MACRO27,
    InputEventCode.KEY_MACRO28,
    InputEventCode.KEY_MACRO29,
    InputEventCode.KEY_MACRO30,
    InputEventCode.KEY_MACRO_RECORD_START,
    InputEventCode.KEY_MACRO_RECORD_STOP,
    InputEventCode.KEY_MACRO_PRESET_CYCLE,
    InputEventCode.KEY_MACRO_PRESET1,
    InputEventCode.KEY_MACRO_PRESET2,
    InputEventCode.KEY_MACRO_PRESET3,
    InputEventCode.KEY_KBD_LCD_MENU1,
    InputEventCode.KEY_KBD_LCD_MENU2,
    InputEventCode.KEY_KBD_LCD_MENU3,
    InputEventCode.KEY_KBD_LCD_MENU4,
    InputEventCode.KEY_KBD_LCD_MENU5,
    InputEventCode.BTN_TRIGGER_HAPPY,
    InputEventCode.BTN_TRIGGER_HAPPY1,
    InputEventCode.BTN_TRIGGER_HAPPY2,
    InputEventCode.BTN_TRIGGER_HAPPY3,
    InputEventCode.BTN_TRIGGER_HAPPY4,
    InputEventCode.BTN_TRIGGER_HAPPY5,
    InputEventCode.BTN_TRIGGER_HAPPY6,
    InputEventCode.BTN_TRIGGER_HAPPY7,
    InputEventCode.BTN_TRIGGER_HAPPY8,
    InputEventCode.BTN_TRIGGER_HAPPY9,
    InputEventCode.BTN_TRIGGER_HAPPY10,
    InputEventCode.BTN_TRIGGER_HAPPY11,
    InputEventCode.BTN_TRIGGER_HAPPY12,
    InputEventCode.BTN_TRIGGER_HAPPY13,
    InputEventCode.BTN_TRIGGER_HAPPY14,
    InputEventCode.BTN_TRIGGER_HAPPY15,
    InputEventCode.BTN_TRIGGER_HAPPY16,
    InputEventCode.BTN_TRIGGER_HAPPY17,
    InputEventCode.BTN_TRIGGER_HAPPY18,
    InputEventCode.BTN_TRIGGER_HAPPY19,
    InputEventCode.BTN_TRIGGER_HAPPY20,
    InputEventCode.BTN_TRIGGER_HAPPY21,
    InputEventCode.BTN_TRIGGER_HAPPY22,
    InputEventCode.BTN_TRIGGER_HAPPY23,
    InputEventCode.BTN_TRIGGER_HAPPY24,
    InputEventCode.BTN_TRIGGER_HAPPY25,
    InputEventCode.BTN_TRIGGER_HAPPY26,
    InputEventCode.BTN_TRIGGER_HAPPY27,
    InputEventCode.BTN_TRIGGER_HAPPY28,
    InputEventCode.BTN_TRIGGER_HAPPY29,
    InputEventCode.BTN_TRIGGER_HAPPY30,
    InputEventCode.BTN_TRIGGER_HAPPY31,
    InputEventCode.BTN_TRIGGER_HAPPY32,
    InputEventCode.BTN_TRIGGER_HAPPY33,
    InputEventCode.BTN_TRIGGER_HAPPY34,
    InputEventCode.BTN_TRIGGER_HAPPY35,
    InputEventCode.BTN_TRIGGER_HAPPY36,
    InputEventCode.BTN_TRIGGER_HAPPY37,
    InputEventCode.BTN_TRIGGER_HAPPY38,
    InputEventCode.BTN_TRIGGER_HAPPY39,
    InputEventCode.BTN_TRIGGER_HAPPY40,
    InputEventCode.KEY_MIN_INTERESTING
]

const AndroidRelEventCodes = [
    InputEventCode.REL_X,
    InputEventCode.REL_Y,
    InputEventCode.REL_Z,
    InputEventCode.REL_RX,
    InputEventCode.REL_RY,
    InputEventCode.REL_RZ,
    InputEventCode.REL_HWHEEL,
    InputEventCode.REL_DIAL,
    InputEventCode.REL_WHEEL,
    InputEventCode.REL_MISC,
    InputEventCode.REL_RESERVED,
    InputEventCode.REL_WHEEL_HI_RES,
    InputEventCode.REL_HWHEEL_HI_RES
]

const AndroidAbsEventCodes = [
    InputEventCode.ABS_X,
    InputEventCode.ABS_Y,
    InputEventCode.ABS_Z,
    InputEventCode.ABS_RX,
    InputEventCode.ABS_RY,
    InputEventCode.ABS_RZ,
    InputEventCode.ABS_THROTTLE,
    InputEventCode.ABS_RUDDER,
    InputEventCode.ABS_WHEEL,
    InputEventCode.ABS_GAS,
    InputEventCode.ABS_BRAKE,
    InputEventCode.ABS_HAT0X,
    InputEventCode.ABS_HAT0Y,
    InputEventCode.ABS_HAT1X,
    InputEventCode.ABS_HAT1Y,
    InputEventCode.ABS_HAT2X,
    InputEventCode.ABS_HAT2Y,
    InputEventCode.ABS_HAT3X,
    InputEventCode.ABS_HAT3Y,
    InputEventCode.ABS_PRESSURE,
    InputEventCode.ABS_DISTANCE,
    InputEventCode.ABS_TILT_X,
    InputEventCode.ABS_TILT_Y,
    InputEventCode.ABS_TOOL_WIDTH,
    InputEventCode.ABS_VOLUME,
    InputEventCode.ABS_PROFILE,
    InputEventCode.ABS_MISC,
    InputEventCode.ABS_RESERVED,
    InputEventCode.ABS_MT_SLOT,
    InputEventCode.ABS_MT_TOUCH_MAJOR,
    InputEventCode.ABS_MT_TOUCH_MINOR,
    InputEventCode.ABS_MT_WIDTH_MAJOR,
    InputEventCode.ABS_MT_WIDTH_MINOR,
    InputEventCode.ABS_MT_ORIENTATION,
    InputEventCode.ABS_MT_POSITION_X,
    InputEventCode.ABS_MT_POSITION_Y,
    InputEventCode.ABS_MT_TOOL_TYPE,
    InputEventCode.ABS_MT_BLOB_ID,
    InputEventCode.ABS_MT_TRACKING_ID,
    InputEventCode.ABS_MT_PRESSURE,
    InputEventCode.ABS_MT_DISTANCE,
    InputEventCode.ABS_MT_TOOL_X,
    InputEventCode.ABS_MT_TOOL_Y,
]

const AndroidSwEventCodes = [
    InputEventCode.SW_LID,
    InputEventCode.SW_TABLET_MODE,
    InputEventCode.SW_HEADPHONE_INSERT,
    InputEventCode.SW_RFKILL_ALL,
    InputEventCode.SW_RADIO,
    InputEventCode.SW_MICROPHONE_INSERT,
    InputEventCode.SW_DOCK,
    InputEventCode.SW_LINEOUT_INSERT,
    InputEventCode.SW_JACK_PHYSICAL_INSERT,
    InputEventCode.SW_VIDEOOUT_INSERT,
    InputEventCode.SW_CAMERA_LENS_COVER,
    InputEventCode.SW_KEYPAD_SLIDE,
    InputEventCode.SW_FRONT_PROXIMITY,
    InputEventCode.SW_ROTATE_LOCK,
    InputEventCode.SW_LINEIN_INSERT,
    InputEventCode.SW_MUTE_DEVICE,
    InputEventCode.SW_PEN_INSERTED,
    InputEventCode.SW_MACHINE_COVER,
]

// Various miscellaneous event types.
const AndroidMscEventCodes = [
    InputEventCode.MSC_SERIAL,
    InputEventCode.MSC_PULSELED,
    InputEventCode.MSC_GESTURE,
    InputEventCode.MSC_RAW,
    InputEventCode.MSC_SCAN,
    InputEventCode.MSC_TIMESTAMP,
]

const AndroidLedEventCodes = [
    InputEventCode.LED_NUML,
    InputEventCode.LED_CAPSL,
    InputEventCode.LED_SCROLLL,
    InputEventCode.LED_COMPOSE,
    InputEventCode.LED_KANA,
    InputEventCode.LED_SLEEP,
    InputEventCode.LED_SUSPEND,
    InputEventCode.LED_MUTE,
    InputEventCode.LED_MISC,
    InputEventCode.LED_MAIL,
    InputEventCode.LED_CHARGING,
]

// Autorepeat values
const AndroidRepEventCodes = [
    InputEventCode.REP_DELAY,
    InputEventCode.REP_PERIOD,
]

// Sounds
const AndroidSndEventCodes = [
    InputEventCode.SND_CLICK,
    InputEventCode.SND_BELL,
    InputEventCode.SND_TONE,
]

// MORE LABEL. Found in input.h
const AndroidMtToolEventCodes = [
    InputEventCode.MT_TOOL_FINGER,
    InputEventCode.MT_TOOL_PEN,
    InputEventCode.MT_TOOL_PALM,
    InputEventCode.MT_TOOL_DIAL,
]

const AndroidFfEventCodes = [
    InputEventCode.FF_STATUS_STOPPED,
    InputEventCode.FF_STATUS_PLAYING,
]

const AndroidPwrEventCodes = [];

const AndroidFfStatusEventCodes = [
    InputEventCode.FF_RUMBLE,
    InputEventCode.FF_PERIODIC,
    InputEventCode.FF_CONSTANT,
    InputEventCode.FF_SPRING,
    InputEventCode.FF_FRICTION,
    InputEventCode.FF_DAMPER,
    InputEventCode.FF_INERTIA,
    InputEventCode.FF_RAMP,
    InputEventCode.FF_EFFECT_MIN,
    InputEventCode.FF_EFFECT_MAX,
    InputEventCode.FF_SQUARE,
    InputEventCode.FF_TRIANGLE,
    InputEventCode.FF_SINE,
    InputEventCode.FF_SAW_UP,
    InputEventCode.FF_SAW_DOWN,
    InputEventCode.FF_CUSTOM,
    InputEventCode.FF_WAVEFORM_MIN,
    InputEventCode.FF_WAVEFORM_MAX,
    InputEventCode.FF_GAIN,
    InputEventCode.FF_AUTOCENTER,
    InputEventCode.FF_MAX_EFFECTS,
]

export default class InputEventType  extends EncodedToken {

    static readonly EV_SYN = new InputEventType(
        {key: "EV_SYN", value: 0x00, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidSynEventCodes,
            description: "Serve as delineators between distinct events, which can be separated either temporally or " +
                "spatially. An example of spatial separation can be observed in the multitouch protocol."});
    static readonly EV_KEY = new InputEventType(
        {key: "EV_KEY", value: 0x01, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidSynEventCodes,
            description: "Describe state changes of keyboards, buttons, or other key-like devices."});
    static readonly EV_REL = new InputEventType(
        {key: "EV_REL", value: 0x02, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidRelEventCodes, description: "Describe movements on a relative axis."});
    static readonly EV_ABS = new InputEventType(
        {key: "EV_ABS", value: 0x03, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidAbsEventCodes, description: "Describe movements on a absolute axis."});
    static readonly EV_MSC = new InputEventType(
        {key: "EV_MSC", value: 0x04, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidMscEventCodes, description: "Miscellaneous input data that don't fit into other types."});
    static readonly EV_SW = new InputEventType(
        {key: "EV_SW", value: 0x05, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidSwEventCodes, description: "Describe some Input Switch update."});
    static readonly EV_LED = new InputEventType(
        {key: "EV_LED", value: 0x11, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidLedEventCodes, description: "Turn LEDs on devices on and off."});
    static readonly EV_SND = new InputEventType(
        {key: "EV_SND", value: 0x12, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidSndEventCodes, description: "Output sound to devices."});
    static readonly EV_REP = new InputEventType(
        {key: "EV_REP", value: 0x14, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidRepEventCodes, description: "Used for autorepeating devices."});
    static readonly EV_FF = new InputEventType(
        {key: "EV_FF", value: 0x15, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidFfEventCodes, description: "Send force feedback commands to an input device."});
    static readonly EV_PWR = new InputEventType(
        {key: "EV_PWR", value: 0x16, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidPwrEventCodes, description: "A special type for power button and switch input."});
    static readonly EV_FF_STATUS = new InputEventType(
        {key: "EV_FF_STATUS", value: 0x17, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
        {codes: AndroidFfStatusEventCodes, description: "Used to receive force feedback device status."});

    metadata?:any;
    codes: InputEventCode[];


    constructor(pParent: any, pConfig:any ) {
        super(pParent);
        if (pConfig != null) {
            for (const i in pConfig) this[i] = pConfig[i];
        }
    }

    static parse(rawTypeValue: number){
        return new InputEventType(
            {key: "DUMMY_TYPE", value: rawTypeValue, byteSize: 2, endianness: Endianness.LITTLE_ENDIAN},
            {code: null, description: "DUMMY INPUT EVENT TYPE"});
    }

    toString() {
        return this.key
    }
}

